// phapluat
// kinhdoanh
// congnghe
// xe
// giaoduc
// suckhoe
// arrayTrains = [
// 	'hà_nội xe_khách bốc_cháy dữ_dội đường vành_đai 3 vks trần hoa_sen đồng_phạm đề_nghị hủy án sơ_thẩm xe_khách cháy dữ_dội đường vành_đai 3 con đuối nước nguy_kịch cha mất_tích hồ sinh_thái làm_giả giấy khám sức_khỏe phó_hiệu trưởng trường y hà giang bắt clip đàn_ông vô_cớ đánh bé trai thang_máy khiến dân mạng sôi_máu tên trộm xui_xẻo nhiễm covid19 điều_trị kẻ_khác trộm kẻ xông đâm phụ_nữ tắm cướp dây_chuyền đầu_thú công_nhân nhặt 83 triệu đồng trả lại_người mất hà nội xe giường nằm bốc_cháy dữ_dội đường vành_đai 3',
// 	'mẩu tin cộng_tác gia_đình vinasun vns kế_hoạch lỗ 115 tỷ đồng 2020 phó tổng_giám đốc satra vissan cạnh_tranh masan nền kinh_tế cạnh_tranh thế_giới khổng_lồ tuột dốc vietnam airline jetstar pacific chung vé máy_bay lập_tức giảm 49000 đồng techpro giải thương hiệu tiêu_biểu châu á – thái_bình dương 2020 – ceo nguyễn đình hiệp vinh lãnh_đạo tiêu_biểu châu á 2020 tiệm nail gốc việt california mừng mở hoạt_động trở_lại 11 apple store mỹ đóng_cửa covid19 cây tiên_yên báo_chí chính_thống kỷ_nguyên truyền_thông xã_hội sức_nặng sự_thật',
// 	'top 5 smartphone công_nghệ sạc siêu nhanh giá siêu hợp_lý lợi_thế sạc nhanh smartphone báo_chí bắt_kịp nhịp đập xã_hội nâng_cấp đáng_giá mitsubishi xpander 2020 ra_mắt việt_nam 7 mẹo tăng_tốc iphone nháy_mắt honor 30 lite 5g cụm ba camera 48mp nokia 83 5g đẹp long_lanh snapdragon 765g 8gb ram camera 64mp hé lộ giá_bán hấp_dẫn phân_tích thực_trạng phát thải khí nhà_kính việt_nam niềm_tin công_chúng cơ_quan truyền_thông quân_đội pháp tổ_hợp máy_bay lái trinh_sát spy ranger đầu_tiên',
// 	'ngắm phiên_bản đặc_biệt range rover fifty ảnh_hưởng dịch giới nhà_giàu hàn vung tiền sắm xe sang trung_quốc chuộng thương_hiệu ô_tô vụ triệu_hồi xe dính lỗi thị_trường việt 6 gần 20000 xe ford ranger everest gia_hạn bảo_hành hiện_tượng rò_rỉ dầu nâng_cấp đáng_giá bmw 330i msport 2020 đánh_giá nhanh mazda6 2020 đối_thủ xứng tầm toyota camry honda accord porsche 968 phạt kéo_theo bồn_tắm quá_khổ hãng xe biến công_nhân thành người_máy lý_do soi toyota granvia 2020 giá 3 tỷ việt_nam',
// 	'xây_dựng thêm 30 sân_chơi năng_động việt_nam trẻ_em nghèo ra_mắt tạp_chí nghiên_cứu khoa_học thanh_niên viết báo tính xây_dựng nâng_cao chất_lượng giáo_dục vùng_sâu cô_gái khiếm_thị ước_mơ trở_thành nhà_báo nhà_báo trần bá dung báo thời chính_trị samsung tổ_chức đợt tuyển_dụng nhân_sự việt_nam đại_dịch covid19 thúc_đẩy chuyển_đổi giáo_dục bắt_nhịp kỳ thi tốt_nghiệp thpt 2020 tấm vé vào_đời lịch nghỉ_hè khai_giảng học_sinh địa_phương khác_nhau thế_nào',
// 	'bác_sĩ thực_hiện ca_mổ hiếm gặp cứu em_bé 2 tuổi nuốt 2 viên nam_châm thực_phẩm nấu chín dễ mất hết chất ăn_sống tốt gấp tỷ phi_công tự thở khí phòng 2424 đề_xuất xin nước hạ độc cơ_thể tuyệt_đối đừng trước_khi ngủ nuốt trúng mảnh gương vỡ bé trai 10 tuổi liên_tục ói máu 327 bệnh_nhân mắc covid19 công_bố khỏi bệnh thông_tin bé sơ_sinh bỏ_rơi hố_ga 12 điều_trị chồng rời quê làm_mướn gặp cơn bạo_bệnh vợ nghèo 5 con nước_mắt ngắn dài bất_lực novartis ngừng thử_nghiệm thuốc chữa sốt_rét đối_với bệnh_nhân mắc covid19 thở miệng ngủ có_thể gây sâu_răng',
// ]
// arrayTrains = [
// 	'bắt_giữ đối_tượng vận chuyển_pháo trái_phép khu_vực biên_giới tỉnh quảng_trị hà nội xe giường nằm bốc_cháy dữ_dội đường vành_đai 3 hà_nội xe_khách bốc_cháy dữ_dội đường vành_đai 3 vận_động viên marathon nước cuốn tử_vong ô_tô khách giường nằm bốc_cháy trơ khung đường vành_đai 3 hà_nội vks trần hoa_sen đồng_phạm đề_nghị hủy án sơ_thẩm xe_khách cháy dữ_dội đường vành_đai 3 con đuối nước nguy_kịch cha mất_tích hồ sinh_thái làm_giả giấy khám sức_khỏe phó_hiệu trưởng trường y hà giang bắt clip đàn_ông vô_cớ đánh bé trai thang_máy khiến dân mạng sôi_máu tên trộm xui_xẻo nhiễm covid19 điều_trị kẻ_khác trộm kẻ xông đâm phụ_nữ tắm cướp dây_chuyền đầu_thú công_nhân nhặt 83 triệu đồng trả lại_người mất hà nội xe giường nằm bốc_cháy dữ_dội đường vành_đai 3 bạn_bè thương_tiếc chia_buồn nam vận_động viên tử_vong tham_gia giải chạy dalat ultra trail lâm_đồng hà_nội truy_nã bị_cáo bỏ_trốn khỏi phiên tòa hà đông điện_thoại cầu_cứu bé gái 13 tuổi mất_tích bộ ca kiểm_tra mặt công_tác ca 5 đầu 2020 ca tỉnh đắk nông sẵn_sàng sẻ chia giọt_máu hồng bắt hiệu_phó trường y làm_giả giấy khám sức_khỏe',
// 	'mẩu tin cộng_tác gia_đình vinasun vns kế_hoạch lỗ 115 tỷ đồng 2020 phó tổng_giám đốc satra vissan cạnh_tranh masan nền kinh_tế cạnh_tranh thế_giới khổng_lồ tuột dốc vietnam airline jetstar pacific chung vé máy_bay lập_tức giảm 49000 đồng techpro giải thương hiệu tiêu_biểu châu á – thái_bình dương 2020 – ceo nguyễn đình hiệp vinh lãnh_đạo tiêu_biểu châu á 2020 tiệm nail gốc việt california mừng mở hoạt_động trở_lại 11 apple store mỹ đóng_cửa covid19 cây tiên_yên báo_chí chính_thống kỷ_nguyên truyền_thông xã_hội sức_nặng sự_thật apple đóng một_số cửa_hàng điểm_nóng covid19 mỹ buôn thất_nghiệp lãi quan_viên kinh_doanh cá ngoại giá rẻ trẻ cố trở_thành bill gates 21 tỷ usd biến mất bí_ẩn ceo tập_đoàn đức từ_chức miệt_mài cải_tạo đồi hoang cựu_binh thu_nhập gần tỉ khát_vọng việt_nam thế_giới nữ nhà_báo trẻ giàu việt_nam lọt top 500 tỷ_phú thế_giới shark đỗ liên đâu mục_tiêu cuộc_sống nhà_vườn du_lịch bọn trẻ ngồi ghế nóng 8x tổng_giám đốc tập_đoàn tỷ usd',
// 	'xây_dựng tòa_soạn hội_tụ kỷ_nguyên 40 top 5 smartphone công_nghệ sạc siêu nhanh giá siêu hợp_lý bứt phá đường đua tìm_kiếm vaccine ngừa covid19 vietbank hội công_nghệ tp hồ chí minh ký biên_bản ghi_nhớ nghiên cứu ứng dụng công_nghệ lợi_thế sạc nhanh smartphone độc_đáo tấm khiên không_khí vô_hình bảo_vệ hành_khách khỏi covid19 mất hỏng thẻ bảo_hiểm y_tế thế_nào cấp điện_thoại báo_chí bắt_kịp nhịp đập xã_hội nâng_cấp đáng_giá mitsubishi xpander 2020 ra_mắt việt_nam 7 mẹo tăng_tốc iphone nháy_mắt honor 30 lite 5g cụm ba camera 48mp nokia 83 5g đẹp long_lanh snapdragon 765g 8gb ram camera 64mp hé lộ giá_bán hấp_dẫn phân_tích thực_trạng phát thải khí nhà_kính việt_nam niềm_tin công_chúng cơ_quan truyền_thông quân_đội pháp tổ_hợp máy_bay lái trinh_sát spy ranger đầu_tiên ưu thế_và triển_vọng phương_tiện chiến_đấu mặt_đất chạy_điện siêu trực_thăng sb1 defiant bứt phá tốc_độ 383 kmh hướng_dẫn kiểm_tra tin nhắn điện_thoại máy_tính cực đơn_giản mỹ nga trung_quốc cuộc_đua pháo điện_từ viễn_tưởng thực_tế cá_nhân hà_nội thu_nhập 140 tỷ đồng_từ kinh_doanh phần_mềm',
// 	'ngắm phiên_bản đặc_biệt range rover fifty ảnh_hưởng dịch giới nhà_giàu hàn vung tiền sắm xe sang trung_quốc chuộng thương_hiệu ô_tô vụ triệu_hồi xe dính lỗi thị_trường việt 6 gần 20000 xe ford ranger everest gia_hạn bảo_hành hiện_tượng rò_rỉ dầu nâng_cấp đáng_giá bmw 330i msport 2020 đánh_giá nhanh mazda6 2020 đối_thủ xứng tầm toyota camry honda accord porsche 968 phạt kéo_theo bồn_tắm quá_khổ hãng xe biến công_nhân thành người_máy lý_do soi toyota granvia 2020 giá 3 tỷ việt_nam ô_tô nissan giá 400 triệu giá lăn_bánh thấp bất_ngờ giảm 50 phí trước_bạ choáng_ngợp garage sang chảnh showroom siêu xe biệt_thự cường đô_la xem dân_chơi thái lột_xác ford ranger thành siêu bán tải f150 suzuki raider giá mềm lột_xác vẻ_ngoài siêu chất ăn_đứt yamaha exciter 150 honda winner x cận_cảnh phiên_bản đầy hoa_hồng rollsroyce phantom crv mẫu ôtô bán_chạy honda việt_nam mẫu xe bay du_lịch pulse evtol tương_lai ưu_đãi 40 triệu đồng giá lăn_bánh suzuki ertiga limited bao_nhiêu siêu suv lamborghini urus màu độc 20 tỷ hà thành bmw mercedesbenz dừng hợp_tác xe tự lái',
// 	'dự_kiến học_sinh tựu_trường năm_học 19 xây_dựng thêm 30 sân_chơi năng_động việt_nam trẻ_em nghèo ra_mắt tạp_chí nghiên_cứu khoa_học thanh_niên viết báo tính xây_dựng nâng_cao chất_lượng giáo_dục vùng_sâu cô_gái khiếm_thị ước_mơ trở_thành nhà_báo nhà_báo trần bá dung báo thời chính_trị samsung tổ_chức đợt tuyển_dụng nhân_sự việt_nam đại_dịch covid19 thúc_đẩy chuyển_đổi giáo_dục bắt_nhịp kỳ thi tốt_nghiệp thpt 2020 tấm vé vào_đời lịch nghỉ_hè khai_giảng học_sinh địa_phương khác_nhau thế_nào bộ giáo_dục đào_tạo dự_kiến thời_gian học_sinh tựu_trường mùng 19 bộ giáo_dục đào_tạo dự_kiến thời_gian học_sinh tựu_trường mùng 19 75137 dự_án đạt giải cuộc_thi khkt trung_học cấp quốc_gia 2019 2020 141 dự_án tham_dự cuộc thi khoa_học kỹ_thuật 20192020 học_sinh lào cai đoạt giải cuộc_thi khoa_học kỹ_thuật cấp quốc_gia hà_nội tuyên_dương 509 học_sinh giỏi tiêu_biểu khánh hòa hàng nghìn học_sinh tư_vấn nghề du_lịch trường_học tốt qatar tăng học_phí đại_học lộ_trình phù_hợp',
// 	'thực_phẩm cực tốt giúp hồi_phục xoa_dịu cơn đau người_bệnh dạ_dày kháng_thể covid19 tồn_tại tám tuần cơ_thể mắc đối_phó bệnh viêm tai gặp trẻ_nhỏ 327 bệnh_nhân mắc covid19 công_bố khỏi bệnh bệnh suy tủy xương đắk nông bệnh nhân tử_vong bệnh bạch_hầu thực_phẩm nấu chín dễ mất hết chất ăn_sống tốt sức_khỏe bé sơ_sinh bỏ_rơi chuyển xấu phi_công tự thở khí phòng 2424 đề_xuất xin nước hạ độc cơ_thể tuyệt_đối đừng trước_khi ngủ đắk nông phát_hiện ổ dịch bạch_hầu thứ 2 tử_vong nuốt trúng mảnh gương vỡ bé trai 10 tuổi liên_tục ói máu 327 bệnh_nhân mắc covid19 công_bố khỏi bệnh thông_tin bé sơ_sinh bỏ_rơi hố_ga 12 điều_trị novartis ngừng thử_nghiệm thuốc chữa sốt_rét đối_với bệnh_nhân mắc covid19 thở miệng ngủ có_thể gây sâu_răng cứu bé 10 tuổi nuốt mảnh kính vỡ chiều 206 thêm 1 bệnh_nhân công_bố chữa khỏi bệnh việt_nam 16 trường_hợp dương_tính covid19 buổi_tối uống loại nước bình_dân gan tự thải độc đời lo ốm_đau ứng_dụng điện_thoại phát_hiện suy_tim giọng_nói',
// ]
// arrayTrains = [
// 	'thảm án 3 chết bí_ẩn hai anh_em điều_hành đường_dây tín_dụng đen hàng chục tỉ đồng tử_hình kẻ tưới xăng thiêu chết con_riêng vợ bắt nghi phạm truy_nã mang súng 14 viên đạn khởi_tố vụ_án lừa_đảo chiếm_đoạt tài_sản công_ty phi long bán dự_án vẽ quốc_hội quan_điểm chính_thức vụ hồ duy hải khởi_tố 2 thanh_niên hack tài_khoản facebook phó bí_thư huyện_ủy lừa tiền tham_ô 13 tỉ đồng trưởng chi_nhánh công_ty điện_tử lãnh 20 tù chủ tài_khoản mất nhận_thức người_nhà rút_tiền ngân_hàng giành khách chặn xe dùng mã_tấu chém quốc_lộ 1',
// 	'airbus dự_báo hàng_không khó trở_lại như_cũ 2023 lễ_hội trái_cây nhập_khẩu new zealand vinmart giá vàng việt_nam rẻ thế_giới thị_trường lạnh_tanh hà_nội thu_nhập 140 tỉ mạng giới trẻ săn ưu_đãi loạt thương_hiệu đình_đám nhờ thanh_toán tiền_mặt pouyuen nghỉ gần 3000 lao_động công_nhân lâu_năm trợ_cấp khủng samsung việt_nam tuyển lao_động quy_mô agribank phát_hành thẻ chip nội_địa điểm ngắt_mạch giao_dịch ngắt cầu_dao sàn chứng_khoán',
// 	'quản_lý mạng xã_hội trung_quốc xóa phát_ngôn thủ_tướng ấn_độ samsung việt_nam tuyển lao_động quy_mô xem phim lậu mạng khó mạng tmobile mỹ ‘ sập ’ 12 tiếng trung_quốc hoãn phóng vệ_tinh cuối hệ_thống định_vị bắc_đẩu lỗi bất_lợi thiết_lập tiêu_chuẩn 5g mỹ nới luật cấm làm_ăn huawei twitter xóa tài_khoản ủng_hộ bắc_kinh đòi xóa tài_khoản chống_đối spacex phóng thành_công tên_lửa falcon 9 mang 58 vệ_tinh băng thông rộng diễn_đàn reddit mách cách xem youtube quảng_cáo làm_phiền tá hỏa con 7 tuổi vô tài_khoản máy mua đồ_chơi game chục triệu',
// 	'giấc_mơ mua tậu xe trẻ taxi saigontourist cổ_đông yêu_cầu mở thủ_tục phá_sản ôtô chạy bốc_cháy ngùn_ngụt nghi rơm cuốn gầm ưu_đãi thuế nhập_khẩu 0 nguyên_liệu vật_tư linh_kiện sản_xuất ôtô cabin xe container cháy rụi trưa nắng thaco gia_tăng xuất_khẩu linh_kiện ghế ôtô toyota việt_nam triệu_hồi gần 30000 xe camry innova corolla lỗi nguy_hiểm hãng xe ồ_ạt ra_mắt xe hâm_nóng thị_trường ôtô doanh_số ôtô 4 tụt dốc thê_thảm dịch covid19 vinfast bâ ́ t ngơ ̀ kha ́ ch ha ̀ ng đô ̉ i xe cu ̃ lâ ́ y xe mơ ́ i',
// 	'giải_pháp điều_trị ung_thư xử_lý chất_thải tăng giá_trị quả chuối đoạt giải khoa_học hutech thông_báo tuyển_sinh trình_độ thạc_sĩ 2020 đợt 2 sáng nay 206 tư_vấn tuyển_sinh - hướng_nghiệp 2020 quảng_nam tphcm quy_chế quản_lý chăm_sóc cây_xanh trường_học mong học_sinh tựu_trường đúng khai_giảng 59 học_sinh dự_án ấn_tượng thi khoa_học kỹ_thuật quốc_gia học_sinh tiểu_học rơi tầng 2 xuống đất chấn_thương sọ não chọn trường con hậu covid19 tỉnh_táo giai_đoạn cấp_bách vũ_công quang đăng hoa_hậu đỗ mỹ linh mc nguyên khang dự ngày_hội tư_vấn tuyển_sinh tuổi_trẻ 1 huyện 4 thí_sinh chung_kết olympia 3 học_sinh trường',
// 	'bă ́ c kinh bắt nhân_viên giao hàng xe ́ t nghiê ̣ m hết làn da đẹp bệnh_nhân phi_công tự thở bình_thường nóng_lòng quê_nhà who thế_giới giai_đoạn nguy_hiểm covid19 bộ_trưởng y_tế thái_lan tình_nguyện thử vắcxin ngừa covid19 thứ_trưởng bộ y_tế báo_chí làm_cho tin giả tin thất_thiệt đất sống thêm 7 ca covid19 châu âu việt_nam 349 ca bác_sĩ ‘ dỏm ’ xài đại học_giả học chuyên_khoa 1 có_thể virus ổ dịch bắc_kinh vũ hán sang châu âu quay trung_quốc nghiên_cứu ngồi tăng nguy_cơ ung_thư',
// ]
// arrayTrains = [
// 	'thảm án 3 chết bí_ẩn hai anh_em điều_hành đường_dây tín_dụng đen hàng chục tỉ đồng tử_hình kẻ tưới xăng thiêu chết con_riêng vợ bắt nghi phạm truy_nã mang súng 14 viên đạn khởi_tố vụ_án lừa_đảo chiếm_đoạt tài_sản công_ty phi long bán dự_án vẽ quốc_hội quan_điểm chính_thức vụ hồ duy hải khởi_tố 2 thanh_niên hack tài_khoản facebook phó bí_thư huyện_ủy lừa tiền tham_ô 13 tỉ đồng trưởng chi_nhánh công_ty điện_tử lãnh 20 tù chủ tài_khoản mất nhận_thức người_nhà rút_tiền ngân_hàng giành khách chặn xe dùng mã_tấu chém quốc_lộ 1 thuê shipper tận thu tiền đánh_bạc game online rõ trách_nhiệm trại_giam triệu quân_sự bỏ_trốn bị_cáo bỏ chạy trốn_thoát công_an dẫn_giải tòa xử_án bộ tư_pháp lập đoàn thanh_tra toàn_bộ vụ đấu_giá đất đường ‘ nhuệ ’ tiền chơi game 6 thanh_thiếu niên rủ nhau cướp',
// ]
// arrayTrains = [
// 	'thảm án 3 chết bí_ẩn hai anh_em điều_hành đường_dây tín_dụng đen hàng chục tỉ đồng tử_hình kẻ tưới xăng thiêu chết con_riêng vợ bắt nghi phạm truy_nã mang súng 14 viên đạn khởi_tố vụ_án lừa_đảo chiếm_đoạt tài_sản công_ty phi long bán dự_án vẽ quốc_hội quan_điểm chính_thức vụ hồ duy hải khởi_tố 2 thanh_niên hack tài_khoản facebook phó bí_thư huyện_ủy lừa tiền tham_ô 13 tỉ đồng trưởng chi_nhánh công_ty điện_tử lãnh 20 tù chủ tài_khoản mất nhận_thức người_nhà rút_tiền ngân_hàng giành khách chặn xe dùng mã_tấu chém quốc_lộ 1 thuê shipper tận thu tiền đánh_bạc game online rõ trách_nhiệm trại_giam triệu quân_sự bỏ_trốn bị_cáo bỏ chạy trốn_thoát công_an dẫn_giải tòa xử_án bộ tư_pháp lập đoàn thanh_tra toàn_bộ vụ đấu_giá đất đường ‘ nhuệ ’ tiền chơi game 6 thanh_thiếu niên rủ nhau cướp',
// ]
// arrayTrains = [
// 	'thảm án 3 chết bí_ẩn hai anh_em điều_hành đường_dây tín_dụng đen hàng chục tỉ đồng tử_hình kẻ tưới xăng thiêu chết con_riêng vợ bắt nghi phạm truy_nã mang súng 14 viên đạn khởi_tố vụ_án lừa_đảo chiếm_đoạt tài_sản công_ty phi long bán dự_án vẽ quốc_hội quan_điểm chính_thức vụ hồ duy hải khởi_tố 2 thanh_niên hack tài_khoản facebook phó bí_thư huyện_ủy lừa tiền tham_ô 13 tỉ đồng trưởng chi_nhánh công_ty điện_tử lãnh 20 tù chủ tài_khoản mất nhận_thức người_nhà rút_tiền ngân_hàng giành khách chặn xe dùng mã_tấu chém quốc_lộ 1 thuê shipper tận thu tiền đánh_bạc game online rõ trách_nhiệm trại_giam triệu quân_sự bỏ_trốn bị_cáo bỏ chạy trốn_thoát công_an dẫn_giải tòa xử_án bộ tư_pháp lập đoàn thanh_tra toàn_bộ vụ đấu_giá đất đường ‘ nhuệ ’ tiền chơi game 6 thanh_thiếu niên rủ nhau cướp',
// ]
// arrayTrains = [
// 	'cha nữ_sinh giao gà yêu_cầu rõ thai bụng con_gái đâm_chết 2 ép uống rượu ốc chặn_đánh 20 đánh_gục 2 khách karaoke cãi_nhau tiếp_viên bình_tân viện kiểm_sát đề_nghị phạt phúc xo 10 12 tù đánh_chết nhậu vài trăm ngàn đồng boa nữ tiếp_viên karaoke phúc xo kêu_oan cung_cấp dụng_cụ sử_dụng ma_túy đa_số ủy viên ủy ban tư_pháp đề_nghị xem_lại quyết_định giám_đốc thẩm vụ hồ duy hải phúc_thẩm vụ nữ_sinh giao gà bị_cáo hùng ép cung suốt 7 7 đêm truy_tìm huấn hoa_hồng dấu_hiệu vi_phạm bán_hàng đa cấp đoàn giám_sát quốc_hội đánh_giá vụ_án hồ duy hải thiếu_sót vi_phạm nhậu đàn_ông ngoài nghe điện_thoại chết vết đâm_thủng ngực bánh_kẹo chứa ma_túy rao bán mạng khởi_tố bắt_giam nam_sinh giấu bé trai 5 tuổi chết rừng phúc_thẩm vụ nữ_sinh giao gà nữ bị_cáo tóc bỗng bạc trắng vài bắt_giam vợ giám_đốc sở tư_pháp lâm_đồng hành_vi chiếm_đoạt hàng trăm tỉ đồng',
// ]
// arrayTrains = [
// 	'khởi_tố phụ_nữ 14 ‘ gây_rối ’ viện ksnd cấp_cao tphcm điện biên đòi nợ giết hai vợ_chồng chủ_nợ tự_sát thảm án 3 chết bí_ẩn triệu quân_sự vượt_ngục ra_sao hai anh_em điều_hành đường_dây tín_dụng đen hàng chục tỉ đồng tử_hình kẻ tưới xăng thiêu chết con_riêng vợ bắt nghi phạm truy_nã mang súng 14 viên đạn khởi_tố vụ_án lừa_đảo chiếm_đoạt tài_sản công_ty phi long bán dự_án vẽ quốc_hội quan_điểm chính_thức vụ hồ duy hải khởi_tố 2 thanh_niên hack tài_khoản facebook phó bí_thư huyện_ủy lừa tiền tham_ô 13 tỉ đồng trưởng chi_nhánh công_ty điện_tử lãnh 20 tù chủ tài_khoản mất nhận_thức người_nhà rút_tiền ngân_hàng giành khách chặn xe dùng mã_tấu chém quốc_lộ 1 thuê shipper tận thu tiền đánh_bạc game online rõ trách_nhiệm trại_giam triệu quân_sự bỏ_trốn',
// 	'saigontourist group hỗ_trợ đưa bệnh_nhân nước kiến_thức dân tin thanh_toán qr cà thẻ airbus dự_báo hàng_không khó trở_lại như_cũ 2023 lễ_hội trái_cây nhập_khẩu new zealand vinmart giá vàng việt_nam rẻ thế_giới thị_trường lạnh_tanh hà_nội thu_nhập 140 tỉ mạng giới trẻ săn ưu_đãi loạt thương_hiệu đình_đám nhờ thanh_toán tiền_mặt pouyuen nghỉ gần 3000 lao_động công_nhân lâu_năm trợ_cấp khủng samsung việt_nam tuyển lao_động quy_mô agribank phát_hành thẻ chip nội_địa điểm ngắt_mạch giao_dịch ngắt cầu_dao sàn chứng_khoán doanh_nghiệp hoa_kỳ biến đà_nẵng thành đầu_tư hấp_dẫn công_bố dữ_liệu doanh_nghiệp chế biến chế_tạo công_nghiệp hỗ_trợ tướng masan hứa đưa công_ty thế_giới công_nhận kỳ_lân ngành tiêu_dùng ví điện_tử phổ_biến nhờ đáp_ứng nhu_cầu thanh_toán hằng_ngày samsung dời phần_lớn dây_chuyền sản_xuất màn_hình máy_tính sang tphcm',
// 	'đăng_ký dự_thi tốt_nghiệp xét tuyển đại_học thế_nào giải_pháp điều_trị ung_thư xử_lý chất_thải tăng giá_trị quả chuối đoạt giải khoa_học hãy ngừng dạy trẻ cách giết_người sáng 216 ngày_hội tư_vấn tuyển_sinh đại_học cao_đẳng 2020 hà_nội tphcm dạy nhà_báo tương_lai hutech thông_báo tuyển_sinh trình_độ thạc_sĩ 2020 đợt 2 cô_gái đoạt nobel hòa bình học xong đại_học oxford dự_kiến tựu_trường sớm 19 sáng nay 206 tư_vấn tuyển_sinh - hướng_nghiệp 2020 quảng_nam tphcm quy_chế quản_lý chăm_sóc cây_xanh trường_học tphcm trường mầm_non giữ_trẻ hè 167 21-8 mong học_sinh tựu_trường đúng khai_giảng 59 học_sinh dự_án ấn_tượng thi khoa_học kỹ_thuật quốc_gia học_sinh tiểu_học rơi tầng 2 xuống đất chấn_thương sọ não chọn trường con hậu covid19 tỉnh_táo giai_đoạn cấp_bách',
// 	'samsung việt_nam tuyển lao_động quy_mô xem phim lậu mạng khó bkav sản_xuất thành_công camera tích_hợp phân_phối thị_trường mỹ mạng tmobile mỹ ‘ sập ’ 12 tiếng trung_quốc hoãn phóng vệ_tinh cuối hệ_thống định_vị bắc_đẩu lỗi bất_lợi thiết_lập tiêu_chuẩn 5g mỹ nới luật cấm làm_ăn huawei twitter xóa tài_khoản ủng_hộ bắc_kinh đòi xóa tài_khoản chống_đối spacex phóng thành_công tên_lửa falcon 9 mang 58 vệ_tinh băng thông rộng diễn_đàn reddit mách cách xem youtube quảng_cáo làm_phiền tá hỏa con 7 tuổi vô tài_khoản máy mua đồ_chơi game chục triệu thủ_tướng quy_định khu_vực cấm bay hạn_chế tàu_bay lái việt_nam sắp thêm tuyến cáp_quang băng thông siêu khủng doanh_nghiệp khu_vực phía nam tiếp_cận cổng dịch_vụ công_quốc gia twitter xóa 170000 tài_khoản lan tin ca_ngợi trung_quốc fpt play box 2020 giới_thiệu loạt tiện_ích google ra_mắt android 11 tập_trung bảo_mật kiểm_soát kết_nối lời cảnh_báo game nhập_vai bạo_lực bốn mạng thỏa_thuận dùng chung hạ_tầng viễn_thông bkav sản_xuất điện_thoại 4g giá 1 triệu đồng đoàn tỉnh bạc_liêu học kinh_nghiệm xây_dựng đô_thị thông_minh tphcm',
// 	'phát_hiện kháng_thể corona gây xôn_xao giới khoa_học saigontourist group hỗ_trợ đưa bệnh_nhân nước tác_giả ‘ để_yên bác_sĩ hiền ’ gây_sốt 3 phút sơ_cứu đại_dịch đã_qua sắp bệnh_viện chợ_rẫy đề_xuất phương_án đưa bệnh_nhân 91 nước làn da đẹp bệnh_nhân phi_công tự thở bình_thường nóng_lòng quê_nhà who thế_giới giai_đoạn nguy_hiểm covid19 bộ_trưởng y_tế thái_lan tình_nguyện thử vắcxin ngừa covid19 thứ_trưởng bộ y_tế báo_chí làm_cho tin giả tin thất_thiệt đất sống thêm 7 ca covid19 châu âu việt_nam 349 ca bác_sĩ ‘ dỏm ’ xài đại học_giả học chuyên_khoa 1 có_thể virus ổ dịch bắc_kinh vũ hán sang châu âu quay trung_quốc nghiên_cứu ngồi tăng nguy_cơ ung_thư sống chậm yêu_thương',
// 	'giấc_mơ mua tậu xe trẻ taxi saigontourist cổ_đông yêu_cầu mở thủ_tục phá_sản ôtô chạy bốc_cháy ngùn_ngụt nghi rơm cuốn gầm ưu_đãi thuế nhập_khẩu 0 nguyên_liệu vật_tư linh_kiện sản_xuất ôtô cabin xe container cháy rụi trưa nắng thaco gia_tăng xuất_khẩu linh_kiện ghế ôtô toyota việt_nam triệu_hồi gần 30000 xe camry innova corolla lỗi nguy_hiểm hãng xe ồ_ạt ra_mắt xe hâm_nóng thị_trường ôtô doanh_số ôtô 4 tụt dốc thê_thảm dịch covid19 vinfast bâ ́ t ngơ ̀ kha ́ ch ha ̀ ng đô ̉ i xe cu ̃ lâ ́ y xe mơ ́ i kéo_dài chu_kỳ kiểm_định xe_tải xe_khách xe 7 chỗ cháy rụi cao_tốc tphcm trung_lương hãng xe đủ cách chiều_chuộng kéo khách mua xe_hơi hãng xe sản_xuất trở_lại đua giảm_giá vi ̀ sao vâ ̃ n tăng nhâ ̣ p khâ ̉ u xe_hơi giư ̃ a mu ̀ a_di ̣ ch',
// ]
// arrayTrains = [
// 	'khởi_tố phụ_nữ 14 ‘ gây_rối ’ viện ksnd cấp_cao tphcm điện biên đòi nợ giết hai vợ_chồng chủ_nợ tự_sát thảm án 3 chết bí_ẩn triệu quân_sự vượt_ngục ra_sao hai anh_em điều_hành đường_dây tín_dụng đen hàng chục tỉ đồng tử_hình kẻ tưới xăng thiêu chết con_riêng vợ bắt nghi phạm truy_nã mang súng 14 viên đạn khởi_tố vụ_án lừa_đảo chiếm_đoạt tài_sản công_ty phi long bán dự_án vẽ quốc_hội quan_điểm chính_thức vụ hồ duy hải khởi_tố 2 thanh_niên hack tài_khoản facebook phó bí_thư huyện_ủy lừa tiền tham_ô 13 tỉ đồng trưởng chi_nhánh công_ty điện_tử lãnh 20 tù chủ tài_khoản mất nhận_thức người_nhà rút_tiền ngân_hàng giành khách chặn xe dùng mã_tấu chém quốc_lộ 1 thuê shipper tận thu tiền đánh_bạc game online rõ trách_nhiệm trại_giam triệu quân_sự bỏ_trốn',
// 	'saigontourist group hỗ_trợ đưa bệnh_nhân nước kiến_thức dân tin thanh_toán qr cà thẻ airbus dự_báo hàng_không khó trở_lại như_cũ 2023 lễ_hội trái_cây nhập_khẩu new zealand vinmart giá vàng việt_nam rẻ thế_giới thị_trường lạnh_tanh hà_nội thu_nhập 140 tỉ mạng giới trẻ săn ưu_đãi loạt thương_hiệu đình_đám nhờ thanh_toán tiền_mặt pouyuen nghỉ gần 3000 lao_động công_nhân lâu_năm trợ_cấp khủng samsung việt_nam tuyển lao_động quy_mô agribank phát_hành thẻ chip nội_địa điểm ngắt_mạch giao_dịch ngắt cầu_dao sàn chứng_khoán doanh_nghiệp hoa_kỳ biến đà_nẵng thành đầu_tư hấp_dẫn công_bố dữ_liệu doanh_nghiệp chế biến chế_tạo công_nghiệp hỗ_trợ tướng masan hứa đưa công_ty thế_giới công_nhận kỳ_lân ngành tiêu_dùng ví điện_tử phổ_biến nhờ đáp_ứng nhu_cầu thanh_toán hằng_ngày samsung dời phần_lớn dây_chuyền sản_xuất màn_hình máy_tính sang tphcm',
// 	'samsung việt_nam tuyển lao_động quy_mô xem phim lậu mạng khó bkav sản_xuất thành_công camera tích_hợp phân_phối thị_trường mỹ mạng tmobile mỹ ‘ sập ’ 12 tiếng trung_quốc hoãn phóng vệ_tinh cuối hệ_thống định_vị bắc_đẩu lỗi bất_lợi thiết_lập tiêu_chuẩn 5g mỹ nới luật cấm làm_ăn huawei twitter xóa tài_khoản ủng_hộ bắc_kinh đòi xóa tài_khoản chống_đối spacex phóng thành_công tên_lửa falcon 9 mang 58 vệ_tinh băng thông rộng diễn_đàn reddit mách cách xem youtube quảng_cáo làm_phiền tá hỏa con 7 tuổi vô tài_khoản máy mua đồ_chơi game chục triệu thủ_tướng quy_định khu_vực cấm bay hạn_chế tàu_bay lái việt_nam sắp thêm tuyến cáp_quang băng thông siêu khủng doanh_nghiệp khu_vực phía nam tiếp_cận cổng dịch_vụ công_quốc gia twitter xóa 170000 tài_khoản lan tin ca_ngợi trung_quốc fpt play box 2020 giới_thiệu loạt tiện_ích google ra_mắt android 11 tập_trung bảo_mật kiểm_soát kết_nối lời cảnh_báo game nhập_vai bạo_lực bốn mạng thỏa_thuận dùng chung hạ_tầng viễn_thông bkav sản_xuất điện_thoại 4g giá 1 triệu đồng đoàn tỉnh bạc_liêu học kinh_nghiệm xây_dựng đô_thị thông_minh tphcm',
// 	'giấc_mơ mua tậu xe trẻ taxi saigontourist cổ_đông yêu_cầu mở thủ_tục phá_sản ôtô chạy bốc_cháy ngùn_ngụt nghi rơm cuốn gầm ưu_đãi thuế nhập_khẩu 0 nguyên_liệu vật_tư linh_kiện sản_xuất ôtô cabin xe container cháy rụi trưa nắng thaco gia_tăng xuất_khẩu linh_kiện ghế ôtô toyota việt_nam triệu_hồi gần 30000 xe camry innova corolla lỗi nguy_hiểm hãng xe ồ_ạt ra_mắt xe hâm_nóng thị_trường ôtô doanh_số ôtô 4 tụt dốc thê_thảm dịch covid19 vinfast bâ ́ t ngơ ̀ kha ́ ch ha ̀ ng đô ̉ i xe cu ̃ lâ ́ y xe mơ ́ i kéo_dài chu_kỳ kiểm_định xe_tải xe_khách xe 7 chỗ cháy rụi cao_tốc tphcm trung_lương hãng xe đủ cách chiều_chuộng kéo khách mua xe_hơi hãng xe sản_xuất trở_lại đua giảm_giá vi ̀ sao vâ ̃ n tăng nhâ ̣ p khâ ̉ u xe_hơi giư ̃ a mu ̀ a_di ̣ ch',
// 	'đăng_ký dự_thi tốt_nghiệp xét tuyển đại_học thế_nào giải_pháp điều_trị ung_thư xử_lý chất_thải tăng giá_trị quả chuối đoạt giải khoa_học hãy ngừng dạy trẻ cách giết_người sáng 216 ngày_hội tư_vấn tuyển_sinh đại_học cao_đẳng 2020 hà_nội tphcm dạy nhà_báo tương_lai hutech thông_báo tuyển_sinh trình_độ thạc_sĩ 2020 đợt 2 cô_gái đoạt nobel hòa bình học xong đại_học oxford dự_kiến tựu_trường sớm 19 sáng nay 206 tư_vấn tuyển_sinh - hướng_nghiệp 2020 quảng_nam tphcm quy_chế quản_lý chăm_sóc cây_xanh trường_học tphcm trường mầm_non giữ_trẻ hè 167 21-8 mong học_sinh tựu_trường đúng khai_giảng 59 học_sinh dự_án ấn_tượng thi khoa_học kỹ_thuật quốc_gia học_sinh tiểu_học rơi tầng 2 xuống đất chấn_thương sọ não chọn trường con hậu covid19 tỉnh_táo giai_đoạn cấp_bách',
// 	'phát_hiện kháng_thể corona gây xôn_xao giới khoa_học saigontourist group hỗ_trợ đưa bệnh_nhân nước tác_giả ‘ để_yên bác_sĩ hiền ’ gây_sốt 3 phút sơ_cứu đại_dịch đã_qua sắp bệnh_viện chợ_rẫy đề_xuất phương_án đưa bệnh_nhân 91 nước làn da đẹp bệnh_nhân phi_công tự thở bình_thường nóng_lòng quê_nhà who thế_giới giai_đoạn nguy_hiểm covid19 bộ_trưởng y_tế thái_lan tình_nguyện thử vắcxin ngừa covid19 thứ_trưởng bộ y_tế báo_chí làm_cho tin giả tin thất_thiệt đất sống thêm 7 ca covid19 châu âu việt_nam 349 ca bác_sĩ ‘ dỏm ’ xài đại học_giả học chuyên_khoa 1 có_thể virus ổ dịch bắc_kinh vũ hán sang châu âu quay trung_quốc nghiên_cứu ngồi tăng nguy_cơ ung_thư sống chậm yêu_thương',
// ]
// arrayTrains = [
// 	'',
// 	'',
// 	'',
// 	'',
// 	'',
// 	'',
// ]
// arrayTrains = [
// 	'triệt_phá đường_dây ma_túy chung_cư cao_cấp hà_nội tìm_thấy thi_thể bé gái 13 tuổi mất_tích cuộc gọi kêu_cứu gia_đình clip khoảnh_khắc nữ đạo_chích mở cốp xe_máy trộm túi_xách tích_tắc hà_nội khiến bàng_hoàng quyết_liệt giải_pháp xử_lý nạn taxi dừng đỗ cổng bệnh_viện bạch_mai ổ_nhóm tín_dụng đen cho_vay 60 tỷ đồng thu lãi 24 tỷ đồng đàn_ông dúi đầu thẳng_tay tát bé trai khiến cđm phẫn_nộ bđbp quảng_bình liên_tiếp bắt đối_tượng tàng_trữ vận_chuyển ma_túy tổ_chức nhập_cảnh cách_ly 120 du_học sinh lào trở_lại nghệ_an học_tập nổ_súng minneapolis 1 chết 11 bị_thương căn nhà_ở đà_nẵng bốc_cháy đêm 7 gia_đình kịp_thời thoát_thân triệt_phá tụ_điểm đá_gà ăn_tiền rẫy vắng sao_không công_khai thưởng báo_tin bắt triệu quân_sự tìm_thấy thi_thể bé gái 13 tuổi mất_tích ăn_quà vặt khởi_tố vụ thảm_sát 3 chết điện_biên giang_hồ đe_dọa đòi nợ đàn_ông nhảy sông mất_tích thảm án 3 chết nhờ giải_quyết nợ 15 tỷ tây_ninh triệt_phá tụ_điểm đánh_bạc hình_thức lắc tài_xỉu ôtô đẩy xe_máy tóe lửa lao vun_vút đường mỹ tìm_thấy thi_thể bé gái 13 tuổi 3 mất_tích mỹ 10 bắn minneapolis cảnh_sát truy_tìm thủ_phạm',
// 	'báo_chí thời hội_nhập phóng_viên chạy nước_rút nữ tỷ_phú tự_thân thách_thức đối_tác lâu_năm apple fred wilson – đầu_tư thành_công cách ngược warren buffett vì_sao giới trẻ sẵn_sàng bỏ hàng nghìn usd mua đồ supreme về_hưu sớm tuổi 35 kỹ_sư phần_mềm tiết_lộ 3 sai_lầm chết_người khiến hầu_hết chúng_ta không_thể tiết_kiệm doanh_nhân huỳnh uy dũng xây cơ_ngơi nghìn tỷ thế_nào cách hóa giải số_liệu bài báo kinh_tế báo chí_hướng nguyên_tắc 5i samsung dịch_chuyển trung_quốc sang việt_nam tuyển lao_động quy_mô công_cụ cải_tiến kaizen giúp công_ty tnhh dệt may xuất_khẩu minh quang tạo_dựng thương_hiệu uy_tín học_hỏi trưởng_thành sinh_viên việt_nam trẻ vươn_tới … nhà_báo tân_hiệp phát_triển khai chọn_lọc ứng_viên nhân_sự kế_thừa 2020 lão_nông đi_đầu phát_triển kinh_tế trang_trại tuyên_quang phi_công chuyển_nghề trái_tim người_làm báo lên_tiếng báo_chí đa_dạng mô_hình kinh_doanh mô_hình kinh_doanh độc lạ món đồ_đồng nát quay nông tỷ_phú usd việt_nam mở trại nuôi lợn đa_dạng hóa nguồn thu báo_chí',
// 	'báo_chí đại_dịch thách thức thời_đại trung_quốc nga bước đột_phá phát_triển vaccine chống covid19 iphone x đẹp long_lanh giảm_giá kịch sàn việt_nam xuống mức đáy đứng đằng_sau thành công_của faceapp học sinh thái_nguyên giành giải_thưởng cuộc thi khkt cấp quốc_gia fbi hướng_dẫn 3 cách tránh mất tiền ngân_hàng ra_mắt cuốn sách giáo_trình tác_phẩm báo mạng điện_tử trung_quốc nga đạt tiến_triển điều_chế vaccine ngừa covid19 cách tắt tính_năng tự_động dừng phát nhạc tháo tai_nghe airpods faceapp độc_hại cảnh_giác microchip mở_rộng danh_mục sản_phẩm adaptec smartraid adapter cấp_độ phổ_thông thành_tích ấn_tượng apple ios 13 khiến google ghen_tị nữ tổng biên_tập đặc_biệt việt_nam mẹo nhỏ dùng iphone cũng_nên giúp máy chạy nhanh iphone 12 nhỏ iphone se màn_hình clip nữ tổng biên_tập đặc_biệt việt_nam một_mình chăm_sóc 800 gốc bưởi chụp_ảnh nhật_thực chiều 216 bí_quyết thành_công mua xe ô_tô cũ đòi bằng_được thứ cách xóa hình_ảnh video danh_bạ trùng_lặp điện_thoại',
// 	'chi_tiết mercedesbenz e 300 amg giá 29 tỷ đồng việt_nam toyota fortuner 2021 nâng_cấp đáng_giá xem toyota innova 2021 thiết_kế sang sienna 2021 siêu suv lamborghini urus 2021 tăng_giá bán xe thể_thao giá rẻ mercedesamg gt 43 khởi_điểm 21 tỷ đồng giá lăn_bánh kia cerato đối_thủ đáng_gờm mazda 3 honda civic chất_lượng sản_phẩm model y tụt dốc telsa chỉ_trích thậm_tệ ô tô_màu sản_xuất thế_giới mẫu xe kỳ_vọng đem thành_công âm_thầm rút_lui khỏi vn thaco đưa tổ_hợp showroom bmw tiêu_chuẩn quốc_tế đà_nẵng hoạt_động hyundai xác ra_mắt tucson lời đe_dọa gửi honda cr - v mazda cx - 5 volkswagen việt_nam công_bố biểu_tượng thương_hiệu volkswagen donkervoort d8 gtojd70 - siêu xe 2g đầu_tiên thế_giới top 10 môtô tốt 2020 honda cbr650r góp_mặt honda pilot 2021 trang_bị hộp_số 9 cấp đấu toyota highlander thời_điểm tắt điều_hòa ô_tô đảm_bảo an_toàn giảm lệ_phí trước_bạ 50 nissan sunny có_giá bao_nhiêu toyota venza 2021 thêm bản gr ngoại_thất thể_thao tesla chỉ_trích thậm_tệ chất_lượng sản_phẩm siêu xe sức_mạnh 3000 mã_lực người_ngoài hành_tinh',
// 	'mê kỹ_thuật ô_tô học đại_học cao_đẳng clip 12 câu_đố kiểm_tra trí_tuệ kỹ_năng sinh_tồn khoảng 10000 học_sinh tham_gia ngày_hội tư_vấn tuyển sinhhướng nghiệp 2020 nghề báo – nghề giàu_có tâm_sự nữ nhà_báo 17 gắn_bó ngành giáo_dục việt_nam đề thi tốt_nghiệp thpt dễ liệu mưa điểm 10 lập quy_hoạch dự_án thành_phố giáo_dục quốc_tế hà_tĩnh vốn đầu_tư 1300 tỷ đồng thầy dạy toán đại_học mỹ xin_lỗi công_khai đề_nghị sinh_viên gốc việt đổi tên thí_sinh thận_trọng điền thông_tin phiếu đăng_ký xét tuyển gần 45 triệu tác_phẩm tham_dự cuộc thi hồ thiếu_nhi thiếu_nhi hồ đh y_dược tphcm dành con nhà_giàu trải lòng nam nhà_báo tự cách_ly 14 ổ dịch bạch_mai ttthích hạnh bình giao_lưu giới_thiệu sách hàng ngàn học_sinh đội nắng ngày_hội tuyển_sinh 2020 công_bố đường dây_nóng hỗ_trợ thi tốt_nghiệp thpt tuyển_sinh 2020 infographic chi_tiết lịch thi môn năng_khiếu báo_chí 2020 450 tình_nguyện viên trường sĩ_quan thông_tin tham_gia hiến máu xã_hội hóa biên_soạn sgk tạo chất_lượng tiết_kiệm ngân_sách đh bách_khoa hà_nội tổ_chức làm_bài kiểm_tra tư_duy 3 địa_phương ninh_thuận sẵn_sàng kỳ thi thpt quốc_gia 2020',
// 	'7 sai_lầm ăn cơm khiến rước đủ bệnh dừng kẻo hối kịp 1 triệu ca nhiễm covid19 brazil who cảnh_báo giai_đoạn nguy_hiểm đại_dịch hạt_dẻ cười món ăn_vặt tốt sức_khỏe bệnh_nhi tử_vong bạch_hầu khẩn_trương cách_ly hàng trăm dân tiến_hành dập dịch lợi_ích củ_cải đường đọc xong mua ăn uống 1 ly nước nóng 2 thời_điểm đào_thải độc_tố giảm cân lợi_ích loại nước có_thể giúp giải_độc uống rượu_bia cực tốt chuyên_gia trung_quốc dịch covid19 bắc_kinh làn_sóng 2 nam phi ghi_nhận ca covid19 tăng kỷ_lục cho_phép sử_dụng dexamethasone ca covid19 romania gia_tăng trở_lại thực_phẩm thần_dược trị táo_bón 7 đồ_uống tăng nguy_cơ mắc ung_thư loại 2 nghe giật_mình bệnh nhân tử_vong người_nhà rút máy thở lấy ổ_cắm điều_hòa mát tại_sao muỗi thích đốt mỹ công_bố thử vắc xin covid19 putin lên_tiếng 5 thực_phẩm ngăn_ngừa ung_thư nhật ưa dùng mỹ dừng thử_nghiệm thuốc sốt_rét trị covid19 cách_ly 355 ngăn_chặn ổ dịch bạch_hầu lây_lan lão_nông sáng_chế máy trợ thở giúp con_trai giành sống đổ_bệnh đột_tử đừng bao_giờ tắm cách',
// ]
arrayTrains = [
	'a',
	'a',
	'a',
	'a',
	'a',
	'a',
]
arrayTrains = [
	'triệt_phá đường_dây ma_túy chung_cư',
	'báo_chí thời hội_nhập phóng_viên',
	'báo_chí đại_dịch thách thức',
	'chi_tiết mercedesbenz e 300',
	'mê kỹ_thuật ô_tô học',
	'7 sai_lầm ăn cơm',
]
