//03/07/2020 ---  crawl data testing
/*Phapluat
Kinhdoanh
Congnghe
Xe
Giaoduc
Suckhoe
*/

let title_initial1= [
	'Giả dịch vụ chuyển tiền Western Union để lừa đảo',
	'Tên trộm quay clip tiệm vàng, đục tường "nẫng" hơn 10 lượng',
	'Chiêu trò của những kẻ giao dịch mua bán hóa đơn trị giá gần 2.000 tỷ đồng',
	'“Hot girl” 9x điều hành đường dây mại dâm giá 3 - 5 triệu/lần',
	'Hai nhóm trai làng hỗn chiến trong đêm, 1 người tử vong',
	'Truy tìm giám đốc sàn thương mại điện tử bán hàng hiệu tại Việt Nam',
	'Đã có kết quả giám định tâm thần “trùm xã hội đen” ở Phú Quốc',
	'Kích vào đường link "lạ", chủ tài khoản ngân hàng "bay" mất 200 triệu đồng',
	'Bị can ngăn, Đường “Nhuệ” đánh nam thanh niên gãy xương hàm dưới',
	'Gần 200 ngày đêm truy dấu đường dây buôn hóa đơn, thu lời bất chính hàng chục tỷ đồng',
]
let title_handling_data1= [
	'giả dịch_vụ chuyển tiền western union lừa_đảo',
	'tên trộm quay clip tiệm vàng đục tường nẫng 10 lượng',
	'chiêu trò kẻ giao_dịch mua_bán hóa đơn trị giá gần 2000 tỷ đồng',
	'hot girl 9x điều_hành đường_dây mại_dâm giá 3 5 triệulần',
	'hai nhóm trai làng hỗn_chiến đêm 1 tử_vong',
	'truy_tìm giám_đốc sàn thương_mại điện_tử bán_hàng hiệu việt_nam',
	'kết_quả giám định tâm_thần trùm xã_hội đen phú_quốc',
	'can_ngăn đường nhuệ đánh nam thanh_niên gãy xương hàm',
	'kích đường link lạ chủ tài_khoản ngân_hàng bay mất 200 triệu đồng',
	'gần 200 ngày_đêm truy dấu đường_dây buôn hóa đơn thu lời bất_chính hàng chục tỷ đồng',
]
let title_initial2= [
	'Hoa mắt với "báu vật" sanh cổ "Tiên lão giáng trần" dáng chưa từng có giá ngang biệt thự',
	'Vay tiền qua app: App "mất hút", người vay bỗng dưng hết nợ',
	'Xe nhập "trượt dốc", ô tô trong nước "vui như mở cờ" vì ưu ái thuế phí',
	'Máy lọc không khí Hitachi Made in Japan EP-PF120J mang đến tầm nhìn mới về không khí sạch',
	'Áo sơ mi Tổng thống Putin bỏ quên tại khách sạn được rao bán 2.500 USD',
	'Bóc trần trò lừa đảo: Xịt sơn lên mít, bơm sữa vào dừa',
	'Các nước Đông Nam Á ganh đua “hút” nhà sản xuất nước ngoài rời Trung Quốc',
	'Mê đắm "nữ hoàng" chim Việt, đại gia Singapore vung tiền tỷ không mua nổi',
	'Nền kinh tế phụ thuộc nặng nề nhất vào Trung Quốc đang dần “thoát ly”',
	'Cherry Nhật đắt kỷ lục, về Việt Nam giá 6,6 triệu đồng/kg',
]
let title_handling_data2= [
	'hoa_mắt báu_vật sanh cổ tiên lão giáng_trần dáng giá ngang biệt_thự',
	'vay tiền app app mất_hút vay bỗng_dưng hết nợ',
	'xe nhập trượt dốc ô_tô nước vui mở_cờ ưu_ái thuế phí',
	'máy lọc không_khí hitachi made in japan eppf120j mang tầm_nhìn không_khí sạch',
	'áo sơ_mi tổng_thống putin bỏ_quên khách_sạn rao bán 2500 usd',
	'bóc_trần trò lừa_đảo xịt sơn mít bơm sữa dừa',
	'nước đông_nam á ganh_đua hút sản_xuất nước_ngoài rời trung_quốc',
	'mê_đắm nữ_hoàng chim việt đại_gia singapore vung tiền tỷ mua nổi',
	'nền kinh_tế phụ_thuộc nặng_nề trung_quốc dần thoát_ly',
	'cherry nhật đắt kỷ_lục việt_nam giá 66 triệu đồngkg',
]
//
let title_handling_data1 = [
	'tòa hà_nội xử vụ giết người_ở đồng_tâm 8',
	'giả dịch_vụ chuyển tiền western union lừa_đảo',
	'tên trộm quay clip tiệm vàng đục tường nẫng 10 lượng',
	'chiêu trò kẻ giao_dịch mua_bán hóa đơn trị giá gần 2000 tỷ đồng',
	'hot girl 9x điều_hành đường_dây mại_dâm giá 3 5 triệulần',
	'hai nhóm trai làng hỗn_chiến đêm 1 tử_vong',
	'truy_tìm giám_đốc sàn thương_mại điện_tử bán_hàng hiệu việt_nam',
	'kết_quả giám định tâm_thần trùm xã_hội đen phú_quốc',
	'can_ngăn đường nhuệ đánh nam thanh_niên gãy xương hàm',
	'kích đường link lạ chủ tài_khoản ngân_hàng bay mất 200 triệu đồng',
]
let title_handling_data2 = [
	'hoa_mắt báu_vật sanh cổ tiên lão giáng_trần dáng giá ngang biệt_thự',
	'hitachi ưu_đãi mua sản_phẩm tủ_lạnh công_nghệ ngăn chân_không',
	'chương_trình kích_cầu cơ_hội dn đưa hàng kênh bán_lẻ hiện_đại',
	'vietinbank nâng_cao chất_lượng tín_dụng đảm_bảo hoạt_động an_toàn hiệu_quả',
	'xe nhập trượt dốc ô_tô nước vui mở_cờ ưu_ái thuế phí',
	'bóc_trần trò lừa_đảo xịt sơn mít bơm sữa dừa',
	'nước đông_nam á ganh_đua hút sản_xuất nước_ngoài rời trung_quốc',
	'mê_đắm nữ_hoàng chim việt đại_gia singapore vung tiền tỷ mua nổi',
	'nền kinh_tế phụ_thuộc nặng_nề trung_quốc dần thoát_ly',
	'cherry nhật đắt kỷ_lục việt_nam giá 66 triệu đồngkg',
]
let title_handling_data3 = [
	'vinsmart smartphone 5g chip bảo_mật lượng_tử duy_nhất việt_nam',
	'samsung sắp smartphone pin gần 7000mah',
	'lạ sầu_riêng có_thể sạc điện_thoại nhanh ngoài sức tưởng_tượng',
	'chặn cuộc gọi rác cò bảo_hiểm nhà_đất',
	'coocaa chính_thức ra_mắt dòng sản_phẩm 0707 shopee',
	'công_nghệ giúp xã_hội duy_trì hoạt_động đại_dịch covid19',
	'1 dùng xác_thực thông_tin cá_nhân ví điện_tử',
	'lộ giá_bán galaxy note20 galaxy fold 2 samsung',
	'apple ý_kiến dùng tin_đồn loại_bỏ sạc iphone 12',
	'chùm ứng_dụng công_cụ học tiếng smartphone nổi_bật tuần',
]
let title_handling_data4 = [
	'văn hóa đỗ xe việt – đâu ý_thức',
	'lamborghini thiết_kế du_thuyền 4000 mã_lực giá 3 triệu usd',
	'xem xe honda e sạc điện tesla model 3',
	'xe sang mercedesbenz bmw đua giảm_giá kéo khách_hàng',
	'giảm 50 phí trước_bạ xe sedan hạng b hưởng lợi',
	'ford mẫu xe_con hạng sang',
	'tình_huống ô_tô tải đấu đầu xe container ngã_tư gây tranh_cãi',
	'tài_xế xe_tải dũng_cảm đá vỡ cửa_kính cứu kẹt ô_tô cháy',
	'tesla phủ_nhận sa_thải nhân_viên làm_việc tại_nhà',
	'suzuki chính_thức ra_mắt xl7 hoàn_toàn suv 7 chỗ mạnh_mẽ sẵn_sàng khởi_đầu',
]
let title_handling_data5 = [
	'xã học_sinh nghỉ 1 tuần hạn_chế ngoài phòng_dịch bạch_hầu',
	'thí_sinh đừng bỏ lỡ cơ_hội sửa_sai',
	'bí_quyết thành công_của thạc_sĩ việt canada thoát_khỏi vùng an_toàn',
	'học_sinh nghỉ_hè 3 vì_sao ủng_hộ',
	'lưu học_sinh nước_ngoài học việt_nam hỗ_trợ kinh_phí',
	'6000 giảng_viên đại_học tham gia_thanh kiểm_tra thi tốt_nghiệp thpt',
	'nữ_sinh lớp 7 bến_tre giành 3 giải cuộc thi thu_hút học_sinh nước',
	'lễ vinh_danh sân_chơi giáo_dục trực_tuyến trạng_nguyên tiếng việt',
	'trung_quốc xu_hướng ôn khắc_nghiệt thi gaokao đại_học tinh_hoa',
	'bộ giáo_dục giải_thích dự_thảo xếp lương giáo_viên',
]
let title_handling_data6 = [
	'đêm gặp vấn_đề coi_chừng nguy_hại',
	'nguy_cơ mắc loại ung_thư',
	'thanh_hóa 14 trường_hợp nghi nhiễm covid19',
	'8 ca dương_tính sarscov2 12 nghìn cách_ly',
	'tầm soát ung_thư dạ_dày thế_nào',
	'bác_sĩ trẻ trải lòng nửa ròng tuyến_đầu chống dịch',
	'đạo_diễn thiên long bát bộ qua_đời ung_thư vòm_họng',
	'4 thứ màu trắng khiến lá_gan khóc_thét lạm_dụng hàng_ngày',
	'bé trai gần 2 tuổi hạt mít chắn_ngang thực_quản',
	'ăn táo tốt đủ đường ngăn_ngừa ung_thư',
]


//7/7/2020
let title_handling_data1 = [
	'tước quyền cha_mẹ ác hổ dữ',
	'hàng chục dân_chơi phê ma_túy toà cao_cấp',
	'bắt tạm giam phụ_nữ tạt xăng đốt chồng mâu_thuẫn',
	'đàn_ông theo_dõi giật ví tiền rời ngân_hàng',
	'huấn hoa_hồng phạt 17 triệu 2 cuốn sách lòe kiếm tiền',
	'đất công_cộng đà_lạt hô biến thành dự_án khách_sạn 5 sao',
	'tên cướp mắt nai sa lưới lén thăm vợ_con 7 lẩn_trốn',
	'trà_vinh khởi_tố gã đàn_ông giết vợ cha vợ',
	'đưa ma_túy lào sang việt_nam bán tử_hình chung_thân',
	'xin học con kẻ_gian đập kính ô_tô trộm 900 triệu đồng',
]
let title_handling_data2 = [
	'hốt_hoảng xe ô_tô chạy cắt đuôi máy_bay lùi nội_bài',
	'đập tam_hiệp khuất_tất khâu phê_duyệt',
	'nhắc khách đeo khẩu_trang nhân_viên nhà_hàng mỹ đánh',
	'sức_hút doanh_nghiệp xanh tiêu_dùng hiện_đại',
	'chim 10 màu độc_nhất việt_nam trả nửa tỷ đồng con bán',
	'tiền trung_quốc tác_động thế_nào doanh_nghiệp việt',
	'kỷ_nguyên đập thủy_điện khổng_lồ trung_quốc hết_thời',
	'bất_ngờ bức tranh phủ bụi lãng_quên 100 giá 100 tỷ đồng',
	'ông_trùm thực_hiện lời_hứa đầu_tư lặng_lẽ bán cổ_phiếu chốt lời',
	'bóc_trần trò lừa_đảo xịt sơn mít bơm sữa dừa',
]
let title_handling_data3 = [
	'vnpt đầu_tư hàng trăm triệu usd đường cáp_quang biển',
	'thương_mại 5g 100 thiết_bị việt_nam 102020',
	'jonathan galindo nhân_vật bí_ẩn gây hoang_mang mạng xã_hội',
	'loạt smartphone giá 2 triệu màn_hình pin khủng đáng cân_nhắc',
	'huawei đối_mặt làn_sóng tẩy_chay',
	'thử_nghiệm thiết_bị 5g việt_nam nghiên cứu thương_mại 102020',
	'vinsmart ra_mắt điện_thoại 5g tích_hợp chip bảo_mật sử dụng công_nghệ điện_toán lượng_tử',
	'samsung sắp smartphone pin gần 7000mah',
	'lạ sầu_riêng có_thể sạc điện_thoại nhanh ngoài sức tưởng_tượng',
	'chùm ảnh iphone 12 đọ dáng iphone se iphone 7',
]
let title_handling_data4 = [
	'doanh_số ford giảm 13 đại_dịch covid19',
	'hé lộ thông_số kỹ_thuật mazda3 turbo 2021',
	'điểm_danh mẫu suv đáng mua hiện_nay',
	'đoàn phân_khối rú ga ầm_ĩ gây tai_nạn đường bỏ_đi',
	'tài_xế mở_đường xe_cứu hỏa dân mạng tán_dương',
	'truyền_hình đức vingroup góp_phần khiến thế_giới thay_đổi cách nhìn việt_nam',
	'tương_lai lốp ô_tô có_thể tự kêu_cứu',
	'xe smart sản_xuất trung_quốc',
	'chủ_tịch hà_nội đàm_phán tổ_chức chặng đua f1 cuối 11',
	'honda winner x ế_ẩm bán thấp đề_xuất 10 triệu đồng',
]
let title_handling_data5 = [
	'tphcm thêm trường đh khoa_học sức_khỏe',
	'trường đại_học thu_hút nguồn tài_trợ khủng nước mỹ',
	'gần kết_thúc năm_học 460 học_sinh đắk nông trở_lại trường',
	'học_phí 4 trường thuộc đh quốc_gia tphcm dự_kiến tăng 2021',
	'bộ giáo_dục đề_nghị 10 bộ ngành phối_hợp tổ_chức thi tốt_nghiệp thpt',
	'tiệc liên_hoan bế_giảng đầy_ắp tình_cảm học_sinh miền núi quảng_nam',
	'10 tài_năng khoa_học công_nghệ trẻ trao giải quả cầu vàng 2019',
	'tphcm số_lượng thí_sinh thi lớp 10 trường phổ_thông năng_khiếu giảm',
	'vẻ đẹp tinh_khôi nữ_sinh trường chu văn an bế_giảng',
	'gia lai_hàng ngàn học_sinh lớp 9 thi môn văn_học kỳ 2 lộ đề',
]
let title_handling_data6 = [
	'bộ y_tế cảnh_báo 2 sản_phẩm thực_phẩm chức_năng giả_mạo thị_trường',
	'phát_hiện trung_quốc nhập_cảnh trái_phép việt_nam',
	'đàn_ông dây diều cứa ngang cổ đứt khí_quản',
	' bé gái 4 tuổi khỉ hàng_xóm cào rách tay chảy mủ',
	'chết bạch_hầu cảnh_báo',
	'14 ca dương_tính sarscov2 dịch lây_lan cộng_đồng',
	'phát_hiện thêm ca nhiễm bạch_hầu ngoài vùng dịch',
	'diệt đám_rối thần_kinh tạng chấm_dứt đau_đớn bệnh_nhân ung_thư',
	'niềng răng invisalign công_nghệ itero 5d đắt xắt miếng',
	'phi_công nước bác_sĩ việt_nam hỗ_trợ chuyến bay',
]
//
let title_handling_data1 = [
	'tước quyền cha_mẹ ác hổ dữ',
	'hàng chục dân_chơi phê ma_túy toà cao_cấp',
	'bắt tạm giam phụ_nữ tạt xăng đốt chồng mâu_thuẫn',
	'đàn_ông theo_dõi giật ví tiền rời ngân_hàng',
	'huấn hoa_hồng phạt 17 triệu 2 cuốn sách lòe kiếm tiền',
	'đất công_cộng đà_lạt hô biến thành dự_án khách_sạn 5 sao',
	'tên cướp mắt nai sa lưới lén thăm vợ_con 7 lẩn_trốn',
	'trà_vinh khởi_tố gã đàn_ông giết vợ cha vợ',
	'đưa ma_túy lào sang việt_nam bán tử_hình chung_thân',
	'xin học con kẻ_gian đập kính ô_tô trộm 900 triệu đồng',
]
let title_handling_data2 = [
	'hốt_hoảng xe ô_tô chạy cắt đuôi máy_bay lùi nội_bài',
	'đập tam_hiệp khuất_tất khâu phê_duyệt',
	'nhắc khách đeo khẩu_trang nhân_viên nhà_hàng mỹ đánh',
	'sức_hút doanh_nghiệp xanh tiêu_dùng hiện_đại',
	'chim 10 màu độc_nhất việt_nam trả nửa tỷ đồng con bán',
	'tiền trung_quốc tác_động thế_nào doanh_nghiệp việt',
	'kỷ_nguyên đập thủy_điện khổng_lồ trung_quốc hết_thời',
	'bất_ngờ bức tranh phủ bụi lãng_quên 100 giá 100 tỷ đồng',
	'ông_trùm thực_hiện lời_hứa đầu_tư lặng_lẽ bán cổ_phiếu chốt lời',
	'bóc_trần trò lừa_đảo xịt sơn mít bơm sữa dừa',
]
let title_handling_data3 = [
	'vnpt đầu_tư hàng trăm triệu usd đường cáp_quang biển',
	'thương_mại 5g 100 thiết_bị việt_nam 102020',
	'jonathan galindo nhân_vật bí_ẩn gây hoang_mang mạng xã_hội',
	'loạt smartphone giá 2 triệu màn_hình pin khủng đáng cân_nhắc',
	'huawei đối_mặt làn_sóng tẩy_chay',
	'thử_nghiệm thiết_bị 5g việt_nam nghiên cứu thương_mại 102020',
	'vinsmart ra_mắt điện_thoại 5g tích_hợp chip bảo_mật sử dụng công_nghệ điện_toán lượng_tử',
	'samsung sắp smartphone pin gần 7000mah',
	'lạ sầu_riêng có_thể sạc điện_thoại nhanh ngoài sức tưởng_tượng',
	'chùm ảnh iphone 12 đọ dáng iphone se iphone 7',
]
let title_handling_data4 = [
	'doanh_số ford giảm 13 đại_dịch covid19',
	'hé lộ thông_số kỹ_thuật mazda3 turbo 2021',
	'điểm_danh mẫu suv đáng mua hiện_nay',
	'đoàn phân_khối rú ga ầm_ĩ gây tai_nạn đường bỏ_đi',
	'tài_xế mở_đường xe_cứu hỏa dân mạng tán_dương',
	'truyền_hình đức vingroup góp_phần khiến thế_giới thay_đổi cách nhìn việt_nam',
	'tương_lai lốp ô_tô có_thể tự kêu_cứu',
	'xe smart sản_xuất trung_quốc',
	'chủ_tịch hà_nội đàm_phán tổ_chức chặng đua f1 cuối 11',
	'honda winner x ế_ẩm bán thấp đề_xuất 10 triệu đồng',
]
let title_handling_data5 = [
	'tphcm thêm trường đh khoa_học sức_khỏe',
	'trường đại_học thu_hút nguồn tài_trợ khủng nước mỹ',
	'gần kết_thúc năm_học 460 học_sinh đắk nông trở_lại trường',
	'học_phí 4 trường thuộc đh quốc_gia tphcm dự_kiến tăng 2021',
	'bộ giáo_dục đề_nghị 10 bộ ngành phối_hợp tổ_chức thi tốt_nghiệp thpt',
	'tiệc liên_hoan bế_giảng đầy_ắp tình_cảm học_sinh miền núi quảng_nam',
	'10 tài_năng khoa_học công_nghệ trẻ trao giải quả cầu vàng 2019',
	'tphcm số_lượng thí_sinh thi lớp 10 trường phổ_thông năng_khiếu giảm',
	'vẻ đẹp tinh_khôi nữ_sinh trường chu văn an bế_giảng',
	'gia lai_hàng ngàn học_sinh lớp 9 thi môn văn_học kỳ 2 lộ đề',
]
let title_handling_data6 = [
	'bộ y_tế cảnh_báo 2 sản_phẩm thực_phẩm chức_năng giả_mạo thị_trường',
	'đàn_ông dây diều cứa ngang cổ đứt khí_quản',
	' bé gái 4 tuổi khỉ hàng_xóm cào rách tay chảy mủ',
	'chết bạch_hầu cảnh_báo',
	'14 ca dương_tính sarscov2 dịch lây_lan cộng_đồng',
	'phát_hiện trung_quốc nhập_cảnh trái_phép việt_nam',
	'phát_hiện thêm ca nhiễm bạch_hầu ngoài vùng dịch',
	'diệt đám_rối thần_kinh tạng chấm_dứt đau_đớn bệnh_nhân ung_thư',
	'niềng răng invisalign công_nghệ itero 5d đắt xắt miếng',
	'phi_công nước bác_sĩ việt_nam hỗ_trợ chuyến bay',
]
let title_handling_data1 = [
]
let title_handling_data2 = [
]
//
let title_handling_data1 = [
	'đi_chơi đảo tàu đủ điều_kiện lưu_thông 3 chết',
	'582020 csgt dừng xe 4 trường_hợp',
	'gã đàn_ông cần_thơ thua_bạc chung tiền đâm_chết',
	'bắt tên trộm dùng súng điện chống trả công_an',
	'hải_quan lạng sơn vướng xử_lý hàng nk chuyển cửa_khẩu dịch_vụ chuyển phát nhanh',
	'sóc trăng bắt_quả tang 40 đối_tượng sử_dụng ma_túy quán karaoke',
	'trộm xe_máy truy_đuổi 9x rút súng bắn trả quyết_liệt',
	'cháy khu_vực tiếp nhiên_liệu sân_bay quân_sự thành_sơn',
	'phạt 8 triệu đồng quái xế lái xe_máy buông 2 tay đánh_võng đường',
	'11 cô_gái tham_gia tiệc ma_túy phòng hát karaoke',
	'cháy quán_ăn nhân_viên thực_khách bỏ_chạy tán_loạn',
	'quảng_trị 2 phụ_nữ nhập_cảnh trái_phép trốn cách_ly covid19',
	'hong_kong hình_sự tội quay lén phát_tán ảnh nhạy_cảm phụ_nữ',
	'thầy_giáo tiếng nước_ngoài trộm điện_thoại đổ_lỗi covid19',
	'tranh_chấp đất_đai dùng choòng đánh đầu_hàng xóm',
	'phạt nặng vi_phạm lĩnh_vực văn hóa quảng_cáo',
	'lao_động tiếp_tục thắng kiện công_ty mía đường sóc_trăng',
	'mỹ đầu_tiên khôi_phục án tử_hình 17',
	'cháy khu tiếp xăng sân_bay quân_sự thành_sơn',
	'hành_khách bức_xúc hủy chuyến bay thông_báo',
	'nghệ an mời uống rượu đánh chủ_nợ nhập_viện',
	'tây spa tiện_tay lấy điện_thoại nữ tiếp_tân',
	'clip hoảng_hồn phụ_nữ lớn_tuổi nằm lái_xe đường quốc_lộ',
	'thừa_thiên huế trộm xe_máy dùng súng điện tự_chế bắn trả lực_lượng truy_đuổi',
	'bỏ 500 nghìn đồng thuê tạt sơn mắm_tôm quán cà_phê mâu_thuẫn',
	'cảnh_sát giao_thông dũng_cảm bắt đối_tượng cướp_giật',
	'hàn_quốc bắt_giữ 3 phái tân thiên_địa liên_quan ổ dịch covid19',
	'thanh_niên bỏ balo đôi dép cầu bình_triệu nhảy xuống sông sài_gòn tự_tử',
	'phá tụ_điểm mại_dâm núp_bóng quán cà_phê quảng_ninh',
	'liên hợp quốc cảnh_báo tình_trạng buôn bán_hàng kém chất_lượng đại_dịch covid19',
	'nghệ an tạm giữ nghi can đổ xăng thiêu sống',
	'trộm xe phát_hiện nam thanh_niên dùng súng điện chống_trả',
	'hà nội gã thanh_niên đánh túi_bụi nữ nhân_viên bảo_vệ chung_cư',
	'cảnh_giác xe_buýt',
	'lựa_chọn số_phận tập 17 đức hóa điên gây tai_nạn trang tát thẳng_tay',
	'tt huế bắt đối_tượng trộm_cắp liên_tỉnh dùng súng chống_trả lực_lượng truy_đuổi',
	'trộm rút súng điện chống trả công_an',
	'triệt_phá trại cai_nghiện game giam_giữ 12 thiếu niên',
	'ba thanh_niên giết_người nghi cầm_đồ thuốc_độc',
	'thông_tin sốc vụ đàn_ông đổ xăng đốt',
	'hải phòng bắt nhanh ổ_nhóm trộm_cắp tài_sản',
	'sợ lộ thông_tin bỏ xác thực tài_khoản ví điện_tử',
	'vụ cựu phó gđ truy sát em_gái thái_nguyên bố_mẹ chết oan_uổng chết mũi dao anh_trai',
	'vi_phạm liên_quan đèn xe mức xử_phạt',
	'khởi_tố phụ_nữ thuê 3 thiếu_niên tạt sơn trộn mắm_tôm quán cà_phê',
	'nguyễn thị hồng sen đầu_thú 2 công_an kiên_trì vận_động',
	'thua bài dùng dao truy sát thắng cược tử_vong',
	'quảng_nam hủy thầu mua_sắm hệ_thống xét_nghiệm real – time pcr tự_động',
	'biển phương_tiện kinh_doanh vận_tải tránh nhập_nhèm phù_hợp xu_thế',
	'phó cục_trưởng csđt tội_phạm ma_túy hà_tĩnh triệt_phá vụ_án',
	'quảng_bình vận_động dân giao_nộp vũ khí vật_liệu nổ',
	'vụ con_trai đánh mẹ đẻ 84 tuổi bại_liệt hải_dương người_chứng kiến sự_việc nói_gì',
	'vụ vợ bị_đơn định nhảy lầu tự_tử tphcm nguyên_đơn quan_hệ tòa_án',
	'phụ_nữ thuê 3 thiếu_niên tạt sơn trộn mắm_tôm quán cà_phê',
	'sóng_ngầm chùa nga_hoàng đệ_tử lê hữu long tiếp_tục gây_hấn',
	'chập điện nhà_hàng bốc_cháy rạng_sáng',
	'cảnh_sát biển phối_hợp bắt_giữ đường_dây vận_chuyển 54 bánh heroin',
	'liên_lạc nguyên giám_đốc sở khoa họccông nghệ đồng_nai',
	'tên trộm dùng súng bắn điện chống_trả công_an',
	'40 sử_dụng ma_túy quán karaoke',
]
let title_handling_data2 = [
	'việt_nam ra_mắt báo_cáo toàn_cầu đổi_mới sáng_tạo báo_chí 20202021',
	'cẩm_nang đổi_mới sáng_tạo giới báo_chí truyền_thông',
	'nghiên_cứu nhân_tố tác_động động_lực làm_việc giảng_viên trường đại_học hiện_nay',
	'gia_tộc đứng đế_chế paris baguette thua_lỗ hàng trăm triệu usd',
	'ford ranger vinh_danh xe đậm chất mỹ 2020',
	'ông_lớn công_nghệ dồn_dập lập kỷ_lục donald trump bước cuộc_chiến',
	'hãng thời_trang 200 năm_tuổi brooks brothers đệ đơn_xin phá_sản',
	'vị ngọt dưa_hấu biên_giới cao_bằng',
	'ra_mắt sách đổi_mới sáng_tạo báo_chí',
	'khấm_khá nhờ trồng hoa_giấy',
	'lý_do vì_sao warren buffett quay trở cuộc_chơi sinh_nhật tuổi 90 dù im hơi lặng tiếng suốt thời_gian dài',
	'nguyễn kỳ philip sáng_lập đảo hải_sản xây_dựng chuỗi bán_lẻ hải_sản chuyên_nghiệp',
	'đô_thị thông_minh lạc_quan điều_kiện',
	'brooks brothers hãng thời_trang 200 năm_tuổi mỹ đệ đơn_xin bảo_hộ phá_sản',
	'nơm_nớp tái đàn dịch_tả heo châu phi',
	'sách cháu gái tổng_thống trump tiết_lộ sự_thật bất_ngờ',
	'nhật bản vụ phá_sản doanh_nghiệp tăng đầu_tiên 11',
	'black friday 2020 dịch covid19',
	'tỷ_phú công_nghệ chiếm đa_số nhóm 7 giàu hành_tinh',
	'tự_ái dân tộc_người sáng_lập toyota trở_thành người_hùng nước nhật',
	'hãng thời_trang lâu_đời nước mỹ brooks brothers nộp đơn_xin phá_sản',
	'trẻ sẵn_sàng chịu_khổ mua giày bán giá',
	'chàng_trai thổi hồn mo_cau',
	'phân_phối apple xiaomi việt_nam nữ chủ_tịch',
	'đầu_tư chăn_nuôi thực_phẩm điểm sáng 2020',
	'kiếm tiền tỉ nhờ bán trầm_hương đơn_giản ước_muốn giúp ấy ngủ_ngon',
	'khởi_động cuộc_thi tìm_kiếm giải_pháp chuyển_đổi việt_nam solutions',
	'nông_dân hà nam bội_thu nắng rát nhờ trồng sen lấy hạt',
	'thương hiệu thời_trang lâu_đời mỹ brooks brothers đệ đơn phá_sản',
	'brooks brothers hãng thời_trang 200 tuổi mỹ đệ đơn_xin phá_sản',
	'thiên_đường startup doanh_nghiệp bệ_phóng biến công_ty gara thành giải pháp trị_giá tỷ usd',
	'tin tây_nguyên nông_trại công_nghệ sạch a – z',
	'điển_hình nông_dân sản_xuất giỏi',
	'digiworld thay chủ_tịch hội_đồng quản_trị',
	'ttxvn ra_mắt cuốn sách đổi_mới sáng_tạo báo_chí toàn_cầu',
	'đồng_phục tài_xế goviet sắp thay_đổi vn tạm_biệt màu đỏ quen_thuộc',
	'goviet trở_thành gojek việt_nam mất',
	'xu_hướng mô_hình kinh_doanh báo_chí toàn_cầu',
	'hộ chăn_nuôi nhỏ_lẻ tái đàn dịch_tả lợn châu phi',
	'benthanh tourist bổ_nhiệm tổng_giám đốc',
	'thiết_kế nghề_nghiệp tương_lai',
	'sợi chuối việt kỳ_vọng chinh_phục thị_trường tỷ usd',
	'cuốn sách hữu_ích dành khởi_nghiệp',
	'grab thích_nghi thế_giới hậu covid19',
	'quy_mô tài_sản 30 tập_đoàn hàn_quốc tăng 100 thập_kỷ',
	'triệu_phú tự_thân công_nghệ chia_sẻ bí_quyết trở_thành cực_kỳ thành_công',
	'giới siêu giàu dạy con giàu ba_đời',
	'google amazon netflix spotify đóng thuế vat indonesia',
	'tuyên_quang làm_giàu nhờ mô_hình nuôi vịt_bầu',
	'công_ty rạng_đông thúc_đẩy chuyển_đổi',
	'tập đoàn ceo ra_mắt khu mua_sắm singapore shoptel',
	'bán mặt đất bán lưng trời nga',
]
let title_handling_data3 = [
	'lục_quân ấn_độ yêu_cầu sỹ quan binh_lính xóa 89 ứng_dụng di_động',
	'video chi_tiết toyota corolla cross sắp việt_nam giá 733 triệu đồng',
	'phát_triển bền_vững năng_lượng tái_tạo thêm cơ_chế hỗ_trợ',
	'tay vsmart star 4 giữ dáng nâng_cấp cấu_hình giá 25 triệu',
	'singapore ứng dụng công_nghệ ekyc đăng_ký thi lái_xe',
	'samsung galaxy note sắp thêm bản nâng',
	'apple đưa công_nghệ màn_hình xịn xò thiết_bị đầu',
	'cú đúp giải_thưởng sinh_viên đh kiến_trúc cuộc thi thiết_kế bệnh viên dã_chiến',
	'tiktok giới_thiệu nền_tảng quảng_cáo doanh_nghiệp',
	'điện năng_lượng tái_tạo đạt 5500 mw',
	'ra_mắt galaxy note20 ultra video trải_nghiệm',
	'nội_soi siêu máy baychở bệnh_nhân phi_công nước',
	'motorola trình_làng smartphone 5g giá_cả phải_chăng moto g 5g plus',
	'tiếng bấc tiếng chì vụ đầu_tư trăm triệu usd ứng_dụng gọi xe',
	'giao_diện đen huyền_bí chính_thức cập bến facebook cách kích hoạt tính_năng',
	'đàn_ông bắt rao bán 2000 chìa khóa ôtô ăn_cắp',
	'chuyển_đổi tăng_tốc nhờ covid19 tiềm_năng fpt ra_sao',
	'ligandfree hkust1 metalorganicframeworkcatalyzed oarylation of phenols by nitroarenes',
	'12 trỗi_dậy năng_lượng tái_tạo châu á thái_bình dương',
	'giới trẻ tphcm xếp_hàng 4h sáng xô_đẩy mua giày 28 triệu đồng',
	'bella hadid bức_xúc phân_biệt chủng_tộc',
	'ứng_dụng nhái tiktok lan_truyền khắp ấn_độ lệnh_cấm',
	'bảo_dưỡng tổng_thể nhà_máy lọc dầu dung quất 128',
	'ngoại_trưởng mỹ chỉ_trích công_ty công_nghệ trung_quốc hành_vi ăn_cắp dữ_liệu',
	'ứng_dụng tiktok ra_mắt nền_tảng quảng_cáo doanh_nghiệp',
	'ươm mầm ý_tưởng khởi_nghiệp nông_nghiệp thời_đại 40',
	'xiaomi ra_mắt redmibook 16',
	'nokia mắc sai_lầm trao cơ_hội huawei ericsson',
	'sắp diễn chương_trình khởi_nghiệp quy_mô',
	'công_ty bgc thái_lan đầu_tư điện mặt_trời việt_nam',
	'đồng_tháp ứng_dụng phần_mềm họp hđnd tỉnh đầu_tiên',
	'vinaphone ra_mắt cuộc gọi chuẩn hd tặng 100 phút miễn_phí',
	'apple biến iphone thành bảo_bối đa di năng không_thể thiếu',
	'nghiên_cứu thành_công hoạt_chất kháng ung_thư hiệu_quả',
	'tặng kèm tai_nghe sạc iphone 12 giá đắt thế_hệ',
	'hãng súng colt edes group dự vietnam defence expo2020',
	'huawei kêu_gọi nước vội_vàng đưa_ra quyết_định mạng 5g',
	'tiềm_năng thương_mại điện_tử hướng truyền_thông xã_hội',
	'cellphone mở bán galaxy s20 bts edition thu_hút hàng trăm khách_hàng đêm',
	'cách đăng bình_luận facebook đường kẻ đầy màu_sắc',
	'điện_lực thái_nguyên góp_sức xdntm',
	'bình_luận cầu_vồng gây_sốt facebook cách bắt trend',
	'iphone 12 pro max nhái xuất_hiện vn giá rẻ khó_tin',
	'nghiên_cứu thành_công bộ lọc không_khí tiêu_diệt virus sarscov2',
	'tphcm tổng_kết mô_hình trình_diễn máy phun thuốc trồng rau',
	'84 việt_nam ca mắc covid19 cộng_đồng',
	'nga chứng_minh robot chiến_đấu vượt mọi đối_thủ',
	'chung tay nguồn năng_lượng bền_vững',
	'pháp sắp đóng tàu sân_bay',
	'3 mẫu điện_thoại đáng mua 2 triệu đồng',
	'poco f2 pro loạt smartphone giảm_giá mạnh đầu 7',
]
let title_handling_data4 = [
	'peugeot 3008 5008 giảm_giá kỷ_lục 1 tỷ đồng cạnh_tranh xe nhật hàn',
	'môtô 300 phân_khối phanh abs 2 kênh giá 115 triệu việt_nam cạnh_tranh yamaha yzfr3',
	'hyundai elantra n line 2021 lộ thiết_kế tuyệt đẹp cạnh_tranh mazda3 turbo',
	'mazda 3 2021 ra_mắt mỹ sử_dụng động_cơ tăng áp 25 turbo',
	'beijing bj80 30 v6t nhái mercedesbenz gclass 115 tỷ đồng',
	'mg motor trở_lại việt_nam khởi_đầu hai mẫu xe trung_quốc',
	'bảng giá xe ô_tô peugeot 72020 giảm_giá 80 160 triệu đồng',
	'loạt xe sang tiền tỷ ra_mắt thị_trường việt',
	'bảng giá xe ô_tô kia 72020 mức giảm 60 triệu đồng',
	'tesla model 3 bất_ngờ thành trào_lưu hàn_quốc',
	'toyota corolla cross 2021 ra_mắt thái_lan sớm có_mặt thị_trường việt_nam',
	'hàng chục nghìn xe ô_tô mazda3 phiên_bản 2020 lỗi hệ_thống phanh',
	'khám_phá audi q5 2021 ra_mắt đổi thiết_kế thêm công_nghệ',
	'thaco giảm giá đồng_loạt mẫu xe mazda cx8 giảm 200 triệu',
	'ducati multistrada 950 s ra_mắt phiên_bản lấy cảm_hứng motogp',
	'volkswagen hỗ_trợ 50 phí trước_bạ phiên_bản luxury',
	'honda forza 300 việt_nam có_giá 345 triệu đồng',
	'lamborghini ra_mắt siêu xe sian roadster siêu mạnh siêu hiếm',
	'giá xe ô_tô hôm_nay 97 ford everest dao động_từ 999 1399 triệu đồng',
	'hyundai i10 n line 473 triệu đồng đấu kia morning gtline',
	'xe suv mg hector plus giá 21000 usd',
	'bảng giá xe ô_tô mazda 72020 thaco giảm_giá 200 triệu đồng',
	'thaco giảm giá đồng_loạt mẫu xe phân_phối thị_trường việt_nam',
	'toyota corolla cross ra_mắt thái_lan sớm có_mặt việt_nam',
	'ngắm thần gió pagani huayra roadster chủ topcar',
	'elon musk ước_mơ hành_trình quá_giang dải ngân hàtesla biến xe_hơi thành món đồ điện_tử hoàn_hảo',
	'ford bronco lộ trọn_vẹn nội_thất ra_mắt học_phong cách f150',
	'corolla cross sắp ra_mắt thị_trường việt_nam',
	'toyota corolla cross 2021 ra_mắt thái_lan cận_kề vn',
	'suv cỡ trung toyota corolla cross sớm ra_mắt thị_trường việt_nam',
	'honda air blade 2020 đẹp hơn_cả vario 150 dàn áo carbon titan cực chất',
	'tài_xế xe công_nghệ nhà_nước hỗ_trợ phí đổi biển xe màu vàng',
	'dòng xe volkswagen tiguan allspace khuyến_mãi gần trăm triệu đồng mùa covid19',
	'cận_cảnh toyota wigo 2020 giá rẻ sắp bán việt_nam',
	'chạy_đua bán xe volkswagen hỗ_trợ 50 phí trước_bạ phiên_bản luxury tiguan allspace',
	'honda crv nhập_khẩu khan hàng chờ bản lắp_ráp',
	'kia optima thế_hệ mỹ có_giá 567 triệu đồng',
	'bảng giá xe lexus 72020 đắt 8340 tỷ đồng',
	'toyota fortuner ưu_đãi 72020 thêm sức cạnh_tranh',
	'mẫu xe trung_quốc sắp ra_mắt việt_nam phiên_bản nâng_cấp',
	'kỹ_năng lùi xe vỉa_hè tài_xế',
	'triệu_hồi xe triệu_hồi mazda3 phiên_bản 2020 lỗi hệ_thống phanh',
	'sao_không chạy xe ô_tô cạn xăng đổ',
	'soi dàn xe khủng xuất_hiện mv rapper binz',
	'cận_cảnh quy_trình sản xuất_siêu xe lamborghini huracan evo',
	'gpx super cub popz 110 bản_sao honda super cub sắp ra_mắt',
	'bảng giá xe mitsubishi 072020 xpander ưu_đãi 2 phiên_bản',
	'mitsubishi pajero sport 2020 bản đặc_biệt 113 tỷ đồng',
	'ford ranger raptor 2022 động_cơ ecoboost 27l mạnh 325 mã_lực',
	'bảng giá xe ô_tô suzuki 7 thêm suv xl7',
	'2021 lexus ls ra_mắt vẻ_ngoài bóng_bẩy kết_hợp thoải_mái công_nghệ hiện_đại',
	'9 trang_bị tiện_nghi bí_ẩn siêu xe',
	'jaguar ipace hệ_thống thông_tin giải_trí sạc ba pha ac tại_nhà',
	'lộ_diện ngoại_thất hyundai elantra n line 2021',
	'bảng giá ô_tô nissan 72020 xe rẻ 448 triệu giảm_giá 40 triệu',
	'porsche 911 gt3 rs 40 bản đặc_biệt bán đấu_giá',
	'trải_nghiệm mercedes eqc 400 – sức_hút suv hạng sang',
	'rollsroyce ra_mắt dòng xe đặc_biệt wraith kryptos thông_điệp mã_hóa',
	'mức giảm_giá lăn_bánh top xe bán_chạy hiện_nay',
	'siêu xe bugatti chiron pur sport 34 triệu usd xuất_hiện thụy_sĩ',
]
let title_handling_data5 = [
	'nữ_sinh ngành luật say_mê hoạt động tình_nguyện',
	'điểm chương_trình tiếp_sức mùa_thi 2020',
	'đà nẵng thí_điểm lắp camera thông_minh trường thpt',
	'tphcm đề_nghị tiếp_tục triển_khai chương_trình sữa học_đường',
	'đại_học kinh_tế quốc_dân chơi khai_trương tiệm nail trường',
	'công_bố quyết_định công_nhận hội_đồng trường đại_học hàng_hải việt_nam',
	'hoàn_thành môn cuối_cùng kỳ thi đại_học khắc_nghiệt thế_giới học_sinh trung_quốc vỡ òa cảm_xúc lao khỏi cổng trường',
	'bộ_trưởng phùng xuân nhạ trường đh tây_bắc khơi_nguồn tài_nguyên tri_thức con_em dân_tộc thiểu',
	'trung tâm phục_hồi chức_năng giáo_dục trẻ_em khuyết_tật tỉnh khánh hòa khen_thưởng 132 học_sinh',
	'trường fulbright hành_trình việt_nam hóa tri_thức toàn_cầu',
	'hà_nội triển_khai tư_vấn cộng_đồng trẻ_em hoàn_cảnh đặc_biệt khó_khăn',
	'điểm tiếp_sức mùa_thi 2020',
	'giải_pháp nghỉ_hè 3 an_toàn quên kiến_thức',
	'tâm_thư du_học sinh việt mỹ',
	'trường đại_học mỹ đổi phương_án dạy_học bảo vệ_sinh viên quốc_tế',
	'hé lộ đề thi học_sinh giỏi quốc_gia môn văn đề sắc dao_cạo thách_thức mọi thí_sinh làm_bài',
	'chương_trình tiếp_sức mùa_thi 2020 sinh_viên hỗ_trợ thí_sinh',
	'bộ trưởng bộ gdđt phùng xuân nhạ làm_việc tỉnh sơn_la',
	'đh kinh_tế quốc_dân mở tiệm nail dành hội chị_em trường đã_thế không_gian sống ảo chill hết nấc',
	'tham_khảo đề ngữ_văn kỳ thi khắc_nghiệt thế_giới',
	'mỹ giảng_dạy trực_tuyến đóng_cửa sinh_viên quốc_tế',
	'kỳ thi đại_học căng_thẳng thầy_giáo tự tay bánh_mì trí_nhớ tặng học_trò',
	'hình_ảnh ngộ_nghĩnh cử_nhân mầm_non chụp_ảnh kỷ_yếu',
	'nhà_trường bắt học_sinh viết giấy nợ giống xã_hội đen',
	'ubnd tphcm đề_nghị tiếp_tục triển_khai chương_trình sữa học_đường',
	'1 triệu sinh_viên có_thể trục_xuất khỏi mỹ trả 14 tỷ học online quê_nhà',
	'sự_thật học_sinh 13 tuổi viết giấy nợ trường',
	'tham_gia nâng chuẩn trình_độ giáo_viên hỗ_trợ 100 học_phí hưởng nguyên lương',
	'giải đề thi lớp 10 môn toán_học sinh lưu_ý dạng toán thực_tế',
	'đề_xuất tựu_trường sớm đối_với trường tư_thục',
	'nữ_sinh lớp 12 nghẹn ngào chia_tay mái trường thpt',
	'ủng_hộ harvard mit đh nổi_tiếng đông sv châu á đâm đơn_kiện chính_quyền trump',
	'lưu_luyến khoảnh_khắc chia_tay tuổi học_trò',
	'chương_trình tiếp_sức mùa_thi 2020 diễn 7 8',
	'cô_gái phú thọ bại não trở_thành sinh_viên đại_học',
	'trường mầm_non vĩnh_thạnh đón công_nhận đạt chuẩn quốc_gia mức_độ 1',
	'bắt_đầu đi_làm iq eq',
	'trường đại_học mỹ phản_đối quy_định thị_thực',
	'hana giang chế_độ eat clean 9 ăn đậu bắp',
	'sắc màu sv 97 9x gây_sốt đẹp sao hoa_ngữ cô_gái trượt đh thành_công nhật',
	'học_sinh khóc nức_nở ôm chặt thầy_cô lễ bế_giảng',
	'đưa đại_học tây_bắc thành trung_tâm đào_tạo nhân_lực chất_lượng',
	'tạo điều_kiện sinh_viên lào sang học_tập quảng_nam',
	'australia hs đo nhiệt_độ trường_học melbourne',
	'áp quy_định đối_với sinh_viên quốc_tế chính_phủ mỹ kiện',
	'100 sĩ_tử trung_quốc chạy khỏi trường_thi động_đất',
	'gần 25 triệu nguyện_vọng xét tuyển đại_học 2020',
	'đại_học harvard mit khởi_kiện chính_quyền mỹ chính_sách đối_với sinh_viên quốc_tế',
	'du_học sinh mỹ thấp_thỏm viễn cảnh_bị trục_xuất',
	'chương_trình tiếp_sức mùa_thi 2020 phá_cách phương_thức',
	'tiếp_sức mùa_thi 63 tỉnh thành_phố',
	'bắt_đầu nộp hồ_sơ dự_thi lớp 6 trường trần đại_nghĩa',
	'học_sinh tự_tin bước_vào kỳ thi tốt_nghiệp thpt 2020',
	'học_sinh tiểu_học tràng_an hào_hứng học_tập ngôi trường khang_trang hiện_đại',
	'ban cán_sự lớp xứng_đáng cộng điểm',
	'thứ_trưởng bộ gdđt nguyễn hữu độ nhiệm_vụ quan_trọng học_sinh ôn_thi tốt',
	'nữ_sinh vĩnh_long mê hoạt_động đoàn thành_tích khủng đáng ngưỡng_mộ',
	'đại_học harvard mit khởi_kiện chính_quyền tổng_thống trump',
	'đại_học chơi mua ôtô sinh_viên thực_hành',
	'giảm áp_lực thi_cử nhờ xét tuyển học_bạ',
]
let title_handling_data6 = [
	'uống bia pha cồn hai nước_ngoài nguy_kịch',
	'uống nước ion kiềm giàu hydro bí_quyết sống thọ nhật',
	'cấp_cứu thành_công 2 bệnh_nhân vỡ gan',
	'quyền bộ_trưởng bộ y_tế làm_việc tỉnh tây_nguyên dịch bạch_hầu',
	'ăn bắp luộc thay cơm 5 kết ngọt hiến hội chị_em thi_nhau bắt_chước',
	'bạch_hầu lan nhanh tây_nguyên 10 triệu liều vắcxin ngừa dịch bùng phát',
	'dấu_hiệu có_thể vô_sinh khám',
	'covid19 lãnh thế_giới cảnh_báo bước lùi hợp_tác toàn_cầu',
	'xảy_ra cơ_thể ngưng ăn_đường',
	'hậu_quả khó lường tự_ý đắp vết_thương thuốc_nam',
	'malaysia 70 ca mắc covid19 triệu_chứng lâm_sàng',
	'10 loài cây độc_nhất thế_giới',
	'món_ăn tưởng_chừng vô_dụng hóa tốt thế mẹ bầu hết ốm_nghén sinh sữa dồi_dào',
	'vắc xin bạch_hầu tiêm phòng trẻ phụ_huynh',
	'cứu kịp_thời người_bệnh kẹt van nhân_tạo huyết_khối',
	'khánh hòa vợ_chồng khách nước_ngoài hôn_mê uống bia ăn hải_sản',
	'170 tổ_chức quốc_tế kêu_gọi jj ngừng bán phấn_rôm baby powder',
	'bác_sĩ phát_hiện ổ sán ruột bệnh_nhân',
	'bệnh_nhân covid19 mỹ vượt 3 triệu',
	'gắp thành_công ổ sán_lá ruột phụ_nữ',
	'50 ca đột_quỵ tăng huyết_áp tử_vong bác_sĩ cách chống căn_bệnh sát_thủ',
	'tổng_thống brazil đặt_cược mạng sống phương_thuốc kỳ_diệu chữa covid19',
	'tphcm tỷ_lệ tiêm_chủng bạch_hầu chậm 15 so_với tiến_độ',
	'phẫu_thuật cắt bướu_giáp khổng_lồ phụ_nữ điện_biên',
	'phụ_nữ đeo khối_u khổng_lồ cổ suốt 30',
	'tin covid19 nóng 972020 thế_giới vượt mốc 12 triệu nhiễm covid19 ấn_độ lao_đao',
	'qua_đời căn_bệnh ung_thư kỳ thi đại_học nữ_sinh chọn hiến xác nội_tạng y_học',
	'nhật_bản phương_thuốc ngừa covid19',
	'tóc cuốn máy cưa_đá bé gái lột một_nửa da_đầu',
	'tt brazil tin thần_dược trị ncov có_thể cứu đất_nước',
	'nga cấp phép loại thuốc thứ 3 trị bệnh_nhân covid19',
	'nga cấp phép thuốc coronavir điều_trị covid19 tổng_thống brazil kiện nhiễm sarscov2 bỏ khẩu_trang',
	'trung_quốc đại lục hàn_quốc tiếp_tục ghi_nhận thêm ca nhiễm covid19',
	'bắt_đầu thử_nghiệm thuốc trị covid19 remdesivir dạng hít',
	'tóc mọc_như nấm mưa lo gãy rụng nhờ thường_xuyên ăn 5 loại rau_quả',
	'16 thực_phẩm giàu vitamin b3 giúp khỏe_mạnh',
	'bệnh_nhân thứ 3 thế_giới chữa khỏi hiv ghép tủy xương',
	'30 phút ép tim 15 shock điện hồi_sinh trái_tim ngừng đập',
	'7 triệu mắc covid19 hồi_phục thế_giới',
	'suýt chết tranh_thủ ăn bát cháo trước_khi mổ đẻ',
	'vòng_tránh thai đâm_thủng trực_tràng tai_nạn đáng_sợ',
	'bệnh tay_chân miệng lây tốc_độ nhanh hà_nội ghi_nhận vài ổ dịch',
	'cập_nhật tình hình_dịch covid19 97',
	'palestine siết_chặt biện_pháp phòng_chống dịch covid19',
	'phó thủ_tướng new zealand ngộ_độc thực_phẩm',
	'cảnh_báo mối lo bệnh_lý suy giãn tĩnh_mạch',
	'dấu_hiệu bệnh vaccine giúp phòng bạch_hầu',
	'kon tum quyết_liệt kiểm_soát ngăn_chặn bệnh bạch_hầu',
	'thêm 2 bệnh_nhân covid19 ra_viện',
	'5 phút yoga 78 yoga thiên_nhiên 11',
	'mỹ tăng chóng mặt_số ca nhiễm covid19 rút khỏi who',
	'bệnh_viện hữu_nghị việt đức cứu sống hai người_bệnh kẹt van nhân_tạo',
	'3 trẻ tử_vong bệnh bạch_hầu hai biến_chứng nguy_hiểm bệnh',
	'dân chủ động phòng_chống bệnh bạch_hầu',
	'trước_khi nhồi_máu não cơ_thể 3 tín_hiệu gấp 4',
	'hãi_hùng ổ sán_lá khổng_lồ bám chặt thành ruột đàn_ông',
	'su_hào ngon đến_mấy nhớ kĩ đại kị kẻo mắc bệnh lúc_nào',
]
//
